### ISSUE TITLE
Issue with setting master log position

### ISSUE THREAD

**Issue by tedbjorling** [geerlingguy/ansible-role-mysql#10]
Hi,

I am trying to configure a Slave node in a Master/Slave setup, running Ansible 1.8.x on Ubuntu, and receive the following error:

failed: [mdldrdb2] => {"failed": true, "parsed": false} Change master Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418041186.92-240395126581341/mysql_replication", line 1949, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418041186.92-240395126581341/mysql_replication", line 367, in main
    changemaster(cursor, chm, chm_params)
  File "/root/.ansible/tmp/ansible-tmp-1418041186.92-240395126581341/mysql_replication", line 165, in changemaster
    cursor.execute(query, chm_params)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''106'' at line 1") OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014

However, setting the following property to a static, numerical value, works. I.e.:

master_log_pos: "{{ master.Position }}"
Changed to 
master_log_pos: 106

This seems to be an issue with the formatting of the data? Please advise

**Comment by geerlingguy** [comment]
It looks like this may have been a result of some of the changes added to the role for replication. I'll try to take a look, but this error looks like it might be a little bit difficult to reproduce.

**Comment by geerlingguy** [comment]
This is annoying to reproduce in a test environment, since it requires setting up a master and slave, getting them out of sync intentionally, then trying to set up the slave again (as happened in the above issue).

But a possible fix might be making sure replication is stopped on the slave prior to running the `CHANGE MASTER` command:

```yaml
- name: Stop replication on the slave.
  mysql_replication: mode=stopslave
  ignore_errors: True
  when: >
    slave|failed
    and (mysql_replication_role == 'slave')
    and (mysql_replication_master != '')
```

**Comment by zx1986** [comment]
```
"failed": true, 
"msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'File'.

The error appears to have been in 'roles/mysql/tasks/replication.yml': line 31, column 3, 
but maybe elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Configure replication on the slave.
  ^ here
```

My Ansible got this error.
Where should I set master.File and master.Position?

**Comment by zx1986** [comment]
I had commented:

```
master_log_pos = "{{ master.Position}}"
master_log_file = "{{ master.File }}"
```

The seems not be used.

**Comment by pserrano** [comment]
I've same problem. I don't  found how script handle master log_pos and log_file variables.
