### ISSUE TITLE
[Support] Priv variable

### ISSUE THREAD

**Issue by generalredneck** [geerlingguy/ansible-role-mysql#102]
How do you go about adding privileges for the same user to 2 different tables... example. one named drupal and one named upgrade? 

I know for a fact I can create 2 different users or add *.* so that the user could work on all the tables... but just curious on how to do the specifics.

**Comment by generalredneck** [comment]
see https://github.com/geerlingguy/ansible-role-mysql/blob/master/defaults/main.yml#L84-L89

**Comment by geerlingguy** [comment]
See the Ansible MySQL module's priv string format, [documented on this page](http://docs.ansible.com/ansible/mysql_user_module.html), for example:

```
# Example privileges string format
mydb.*:INSERT,UPDATE/anotherdb.*:SELECT/yetanotherdb.*:ALL
```

**Comment by generalredneck** [comment]
👍 Thanks tons.
