### ISSUE TITLE
Use loop to define databases (and users)

### ISSUE THREAD

**Issue by cirdan** [geerlingguy/ansible-role-mysql#106]
Hi,
Thank you for your huge work on Ansible roles.
(This is a question, not a bug, and maybe related to my new and partial knowledge of Ansible)
I'm trying to define the databases to be created using facts defined in the target node, and a loop (with_items).
But I can't find where to do this : I can't use a loop inside the vars definition.
You give an example but with one database : how can I dynamically define more than one database ?

Thanks for any help.

**Comment by t4k** [comment]
I think this is an issue for me, too.

TASK: [geerlingguy.mysql | Copy my.cnf global MySQL configuration.] *********** 
<xx.xx.xx.xx> ESTABLISH CONNECTION FOR USER: ubuntu
<xx.xx.xx.xx> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/xx/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 54.218.125.25 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1469751492.5-272091465937540 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1469751492.5-272091465937540 && echo $HOME/.ansible/tmp/ansible-tmp-1469751492.5-272091465937540'
fatal: [xx.xx.xx.xx] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'item' is undefined", 'failed': True}
fatal: [xx.xx.xx.xx] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'item' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

Here is what I have tried in my playbook:

    db_names:
          - one
          - two
          - three
    mysql_databases:
      - name: prefix_{{ item }}_suffix
        with_items: "{{ db_names }}"

and

    mysql_databases:
      - name: prefix_{{ item }}_suffix
        with_items:
          - one
          - two
          - three

**Comment by davidfsmith** [comment]
To create more than one database I use:

    mysql_databases:
      - name: database1
      - name: database2

Which works for me.

**Comment by cirdan** [comment]
@davidfsmith :  You're right, setting this the way you do works, but my problem was to define mysql_databases with some loaded vars.
I found that this can be done with "pre_tasks" : the doc is rather silent about this, but tasks are normally executed *after* roles, except for pre_tasks, so this might be the solution

**Comment by bennyt2** [comment]
I was able to figure this out with help from [this stackoverflow post](http://stackoverflow.com/a/35608380/6839737).

Assume I have the following variables and facts:

Variables
```
username: test_user
password: test_pass
priv: test_priv
```
Facts
```
"groups.apiservers": [
    "192.168.4.30", 
    "192.168.4.31"
],
"groups.webservers": [
    "192.168.4.32", 
    "192.168.4.33"
]
```

This task loops through the facts and adds an object with user information to the `mysql_users` array. You'll need to run this task before you run the `geerlingguy.mysql` role.
```
- name: "Define mysql users"
  set_fact:
    mysql_users: "{{ mysql_users|default({}) + [{'name': username, 'host': item, 'password': password, 'priv': priv }] }}"
  with_items:
    - "{{groups.apiservers}}"
    - "{{groups.webservers}}"
```

The resulting `mysql_users` array looks like this:

```
{
    "host": "192.168.4.30", 
    "name": "test_user", 
    "password": "test_pass", 
    "priv": "test_priv"
}, 
{
    "host": "192.168.4.31", 
    "name": "test_user", 
    "password": "test_pass", 
    "priv": "test_priv"
}, 
{
    "host": "192.168.4.32", 
    "name": "test_user", 
    "password": "test_pass", 
    "priv": "test_priv"
},
{
    "host": "192.168.4.33", 
    "name": "test_user", 
    "password": "test_pass", 
    "priv": "test_priv"
}
```

**Comment by geerlingguy** [comment]
Thanks for posting your thought process and the solution here, and yes, that's probably the best way to get them defined. You could even wrap that into a role if you need to use it in many playbooks so it could be reused (the portion that transforms the data into a list of databases, that is).
