### ISSUE TITLE
mysql path problems with software collections

### ISSUE THREAD

**Issue by cammchugh** [geerlingguy/ansible-role-mysql#107]
I had some trouble installing newer mariadb packages from software collections on CentOS/RHEL. Software collections install under /opt/rh, so the command/shell tasks that execute mysql queries in secure-installation.yml fail due to the mysql binary not being on the normal system path.  I attempted to add /opt/rh/rh-mariadb100/root/bin to the PATH variable at the play level using Ansible's recommended approach:

http://docs.ansible.com/ansible/faq.html#how-can-i-set-the-path-or-any-other-environment-variable-for-a-task-or-entire-playbook

```
environment:
  PATH: "{{ ansible_env.PATH }}:/thingy/bin"
  SOME: value
```

But it seems that recent versions of ansible are preventing this from working as expected. See:
https://github.com/ansible/ansible/issues/14655

In my case, since this is the only version of mysql/mariadb installed, forcing a symlink to the mysql binary to /usr/bin/mysql prior to executing this role solves the issue, but I'm hoping there's a better approach that I'm missing.

**Comment by geerlingguy** [comment]
I'm not a huge fan of Software collections (I figure VMs and/or Docker is a better solution than trying to have more compartmentalized software installations for multiple versions), so I don't know if I can be of much help here.

**Comment by cammchugh** [comment]
Ok, no worries. We typically use software collections to get newer packages than defaults with clients who are paying for RHEL and prefer not to install "unsupported" packages or repos. We seldom install multiple versions, so symlinks will have to do for now.

**Comment by geerlingguy** [comment]
Sounds good; going to leave it open so others can chime in.
