### ISSUE TITLE
Problem restarting mysql service after configuration applied

### ISSUE THREAD

**Issue by CharlyP** [geerlingguy/ansible-role-mysql#11]
Hi,

I'm currently using your role on a Debian wheezy (with vagrant and LXC).
I only set `mysql_databases` and `mysql_users` vars but at the end of the provisioning I get the following error:
```
failed: [default] => {"failed": true}
msg: Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!
```

The corresponding syslog logs are:
```
Dec 12 06:13:46 corep /etc/init.d/mysql[11915]: 0 processes alive and '/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf ping' resulted in
Dec 12 06:13:46 corep /etc/init.d/mysql[11915]: #007/usr/bin/mysqladmin: connect to server at 'localhost' failed
Dec 12 06:13:46 corep /etc/init.d/mysql[11915]: error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Dec 12 06:13:46 corep /etc/init.d/mysql[11915]: Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
Dec 12 06:13:46 corep /etc/init.d/mysql[11915]:
```

Any idea what went wrong during configuration?

**Comment by mb720** [comment]
In the meantime I could get around the issue by setting `mysql_innodb_log_file_size: "5M"`

**Comment by geerlingguy** [comment]
Recent commits that are now in the 1.4.1 release should resolve the issues. The role was working on some installations of Ubuntu (both 12.04 and 14.04), but only due to some particular bits of environment configuration. I've updated the role to work much better cross-platform, and I've also added tests to ensure socket-based connection and TCP-based connection works correctly.

**Comment by mb720** [comment]
Thanks for the fix.
I had to delete ib_logfile0 and ib_logfile1 in /var/lib/mysql/ to make provisioning work using 1.4.1.

**Comment by moreirapontocom** [comment]
After spending about 5 hours working on that, you saved my life, mb720. Thanks a lot.
