### ISSUE TITLE
More permissions issues and possible hint

### ISSUE THREAD

**Issue by debo** [geerlingguy/ansible-role-mysql#111]
Hi Jeff, I wanted to give some additional ingo about the permission issues that many people are reporting in different forms and shapes. I can constantly replicate a permission issue when using mysql 5.6. or 5.7 on Debian Jessie. The role works fine out of the box using MySQL 5.5 though.
The playbook is running with `become: yes` and what seems to be the cause of the breakage is the `overwrite_global_mycnf: yes`, the moment I switch that off everything works fine.

Could it be the case that there are some incompatibilities in the config between 5.5, 5.6 and 5.7? I will investigate further but I thought I was going to share this info with you.

Possible reference to https://github.com/geerlingguy/ansible-role-mysql/issues/34 and https://github.com/geerlingguy/ansible-role-mysql/issues/94

**Comment by debo** [comment]
Hi @geerlingguy to clarify the error I encountered is the same described in the linked issue #34 and #94 possibly others.

You previously mentioned in those tickets that the reason was either the lack of `become: yes` or that the solution was to delete the user's `.my.cnf` and provision again. I tried both without success, and as mentioned in the previous ticket it actually looks like the provided my.cnf that comes with the role is not fully compatible with MySql 5.6 and 5.7; when you set `overwrite_global_mycnf: yes` in fact the service doesn't even start.

I hope that clarifies the situation and help shed some light. I'm not looking for a solution, preventing the config to be overwritten does the trick I was simply sharing my louf thoughts hoping that this might give you some ideas on the why the issue exists and is reported.

Happy to discuss and help further.

**Comment by geerlingguy** [comment]
@debo - Just wondering, is this still an issue? I have been using the role with Ubuntu 16.04 / MySQL 5.7.x, and also with later versions of MariaDB without issue...

In the intervening months, there have been a number of commits which I think cleaned up all the little issues that were still present.

**Comment by debo** [comment]
@geerlingguy I didn't try in a while but as I said, it was almost a non issue, setting the config properly was fixing the apparent problem. I'll keep you posted if I face the problem again.
