### ISSUE TITLE
Mariadb 10.0.23 does not work

### ISSUE THREAD

**Issue by jsharpe** [geerlingguy/ansible-role-mysql#127]
As the authentication for root as changed in the latest version of mariadb then the secure-installation.yml file fails.
failed: [localhost](item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN %28'localhost',)) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.005192", "end": "2016-06-07 20:33:55.139678", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-06-07 20:33:55.134486", "stderr": "ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by corny** [comment]
Please try my workaround: https://gist.github.com/corny/dcf031a8af64c398efdaf0510e0c7566
