### ISSUE TITLE
Restart fails due to unsupported sleep parameter.

### ISSUE THREAD

**Issue by pigulla** [geerlingguy/ansible-role-mysql#128]
Restarting the MySQL service fails because the `systemd` module is used instead of the expected `service` module. The problem is that the former does not support the `sleep` parameter.

Details can be found in ansible/ansible-modules-core#3897.

**Comment by bcoca** [comment]
this should be fixed in devel(future 2.2)  now that the service action plugin removes arguments non understood by the underlying module that gets executed

**Comment by geerlingguy** [comment]
@bcoca - Thanks for the explanation—in that case, I may just hold off on trying to shim a fix, and once 2.2 is out, I'll bump the role's required version to that...

**Comment by geerlingguy** [comment]
2.2 is out, and things are working okay :)
