### ISSUE TITLE
fails when run with --check

### ISSUE THREAD

**Issue by seilting** [geerlingguy/ansible-role-mysql#129]
When I run `ansible-playbook ... --check --diff`, it goes fine until this happens:

    TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***********************
    [DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
    This feature will be removed
    in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
    fatal: [new-staging]: FAILED! => {"failed": true, "msg": "'item' is undefined"}

It doesn't fail without --check. The deprecation warning appears to be related: mysql_anonymouse_hosts is not set in check mode.

I am running ansible 2.1.0.0 on OS X, the target machine is a Ubuntu 14.04.4 VM.

Playbook to demonstrate:

    ---
    - name: Test check mode
      tasks:
        - name: register something
          command: ls /
          register: command_output
          changed_when: false
        - debug: msg="output is {{command_output}}"
    ...

If run with --check, the debug output is:

    output is {u'msg': u'remote module does not support check mode', u'skipped': True, u'changed': False}

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-role-mysql/pull/99

**Comment by geerlingguy** [comment]
Fixed in https://github.com/geerlingguy/ansible-role-mysql/pull/130
