### ISSUE TITLE
InnoDB log size is 5MB even though 64MB is specified

### ISSUE THREAD

**Issue by betrcode** [geerlingguy/ansible-role-mysql#14]
For some reason, my mysql db is created with 5MB InnoDB log file size, even though 64MB is specified. This makes mysql unable to start. Any idea? I saw you had set a 5MB log size in the test folder. 

vagrant@vagrant-ubuntu-trusty-64:~$ sudo mysqld --verbose
150112 15:46:19 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
150112 15:46:19 [Note] Plugin 'FEDERATED' is disabled.
150112 15:46:19 InnoDB: The InnoDB memory heap is disabled
150112 15:46:19 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150112 15:46:19 InnoDB: Compressed tables use zlib 1.2.8
150112 15:46:19 InnoDB: Using Linux native AIO
150112 15:46:19 InnoDB: Initializing buffer pool, size = 256.0M
150112 15:46:19 InnoDB: Completed initialization of buffer pool
InnoDB: Error: log file ./ib_logfile0 is of different size 0 5242880 bytes
InnoDB: than specified in the .cnf file 0 67108864 bytes!
150112 15:46:19 [ERROR] Plugin 'InnoDB' init function returned error.
150112 15:46:19 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
150112 15:46:19 [ERROR] Unknown/unsupported storage engine: InnoDB
150112 15:46:19 [ERROR] Aborting

150112 15:46:19 [Note] mysqld: Shutdown complete

Grateful for any ideas.

**Comment by betrcode** [comment]
Using version 1.4.1 of this role.
{install_date: 'Mon Jan 12 15:38:28 2015', version: 1.4.1}

**Comment by JorisVanEijden** [comment]
Same problem on a CentOS release 6.6 machine.

**Comment by betrcode** [comment]
I've reverted to 1.3.4 for now.

**Comment by geerlingguy** [comment]
I'm looking into this today; it seems that the apt-based MySQL installation in Ubuntu 12.04 and 14.04 automatically starts MySQL after it's installed (using the default/included `my.cnf` file, which sets the log file size at 5M).

In the past, this role was actually/technically broken on Ubuntu, because the config file was copied to `/etc/my.cnf` instead of Ubuntu's default `/etc/mysql/my.cnf`, therefore it was not being used.

On CentOS and RedHat-based distributions, since MySQL isn't started until you _want_ to start it, the log files aren't created, meaning we can safely update the value in `my.cnf` _after_ we install MySQL, and the log files will be created at whatever size is specified. (So to @JorisVanEijden's statement—I just tried the role on a CentOS 6.5 and CentOS 6.6 VM both, and it had no issues on either...).

**Comment by betrcode** [comment]
Yes, I realize it was broken before, but it worked in a way :-)

I figured it looked like mysql started before you got the customized my.cnf in there.

May I suggest that instead of overwriting the default config, you override the configuration by placing a config file in the /etc/mysql/mysql.d/ dir (writing from memory, please confirm the location) BEFORE installing the database using apt? This dir is included by default in the default config file.

That way the file will be there before mysql has a chance to start up, and won't get overwritten by apt.

**Comment by geerlingguy** [comment]
In that case, though, the my.cnf directives would still be used first, correct? Also, this would mean that (again, for Deb/Ubuntu-only), I would need to create the directory structure in addition to copying the template prior to mysql install, correct?

I'm currently trying to get a policy-rc.d solution in place so MySQL simply doesn't launch during install... we'll see how that goes.

**Comment by geerlingguy** [comment]
This issue should be fixed now—on Ubuntu, if MySQL has just been installed, MySQL is stopped, the automatically-generated logfiles are deleted, and then after the new configuration is in place, MySQL is started again so the log files have the correct size.

If you're trying to _change_ the log file size on an existing installation, you'll still need to do that in a different way, likely by stopping mysql and deleting the logfiles in a `pre_task` prior to this role running.

Closing this issue, and I'll release a new tag, 1.4.2, later this morning.

**Comment by betrcode** [comment]
Thanks for resolving this so quickly. I still think my suggestion would work since mysql will parse the entire configuration before using it, but you are right that you would need to create the file and directory structure before.

Benefit: You wouldn't need to stop and delete log files.

Anyway, a pull request would make a better argument I suppose. :-) Probably won't do that anytime soon.

Thanks again!

**Comment by JorisVanEijden** [comment]
Ah yes, this makes sense.
My database must have been started somewhere before the new conf from this role got in.
Thanks for looking into this.

Maybe a note on the readme about changing vars like log size would be helpful?
