### ISSUE TITLE
Mysql replication "Check master replication status" does not use mysql credentials to login to the master

### ISSUE THREAD

**Issue by ikelos** [geerlingguy/ansible-role-mysql#146]
Hi there,

I just started using this to setup replication slaves, and found that when the getmaster call is made, it passes no credentials and therefore fails to login.  This can be resolved by passing the login_user and login_password variables (set to something appropriate) in the "Check master replication status" task of replication.yml.  I'm happy to produce a patch if it would help, but I figured you might want to set the variable naming convention yourself.  Please let me know if you need any further information to get this resolved!  Thanks,

Mike  5:)

**Comment by geerlingguy** [comment]
@ikelos - As long as you're running this role with `become: yes`, or as the `root` user, then the credentials should be automatically picked up through the `.my.cnf` file this role places in the root user's home directory (in lieu of manually setting the `login_*` variables).

See the documentation here: http://docs.ansible.com/ansible/mysql_replication_module.html

I'd rather not add those settings as this role assumes the use of the .my.cnf file elsewhere, and having to add in even more credentials would make the setup and use of replication even more difficult.

If you still can't get this role to work with replication, please let me know; I do know that if you shim this role into existing infrastructure, if you don't configure the password manually the first time in the .my.cnf file, some things (like replication) may not work as expected.

**Comment by ikelos** [comment]
Hi there, I still can't get the replication to work (without the `login_*` variables I mentioned).  The specific task ("Check master replication status.") is delegated to the master and I couldn't find anywhere in the code that the master's `.my.cnf` file was set.  The documentation you linked mentions:

> Both `login_password` and `login_user` are required when you are passing credentials. If none are present, the module will attempt to read the credentials from `~/.my.cnf`, and finally fall back to using the MySQL default login of ‘root’ with no password.

So without a `.my.cnf` on the master or the `login_*` variables, the only way I can see this replication task working is if it were run on databases that allowed a root login with no password.  I checked the source for the mysql_replication module, and it looks as though it has to be delegated (because the master_* variables are only used for the `changemaster` mode, not the `getmaster` mode).

So I can't understand how the slave's local `.my.cnf` file would be used to authenticate by the delegated task on the master?  I tried the replication out, running as root, and ran into this which is why I filed the issue.  Have you been able to successfully replicate servers (that have passwords set for every account) using this module, and if so could you help me figure out how?

**Comment by geerlingguy** [comment]
@ikelos - In my testing/usage, the master (as well as any other host) is managed by this role, so in that case the master's account will also have a valid `.my.cnf` file on _it_ that allows access.

In your case, are you managing all the servers through this role, or just slaves?

**Comment by ikelos** [comment]
Fair enough, I'm not allowed to leave cleartext passwords on the servers, so I have a task to remove that file after using the role.  It seemed like a genuine issue others might run into which is why I reported it, but if you want to leave the role as is then that's fine.  You might want to add documentation about how the authentication all works and that the server is expected to have been built by the same role though, it was quite confusing when I first ran into it...

**Comment by geerlingguy** [comment]
True, and I have encountered the same issue before with some others who had to meet that policy. I think from that perspective, I would definitely consider a PR that adds those two variables in—maybe something like `mysql_replication_login_*` vars?

**Comment by ikelos** [comment]
So, by adding the REPLICATION CLIENT grant to the replication user (that already has to be on the master anyway), this can login and run the command without new variables required.  I've submitted this as pull request #214.
