### ISSUE TITLE
Breaking mysql_replication change in Ansible 2.2.0+

### ISSUE THREAD

**Issue by patrickdoc** [geerlingguy/ansible-role-mysql#152]
2 days ago, the mysql_replication module was changed with this commit (https://github.com/ansible/ansible-modules-extras/commit/fc764553260e02bb7b36bf7c601685206d6f93cf).

This changes the getmaster/getslave functionality to not fail, but rather return a boolean Is_Master/Is_Slave. Thus,the slave tasks at the end of replication.yml will never run.

I think the "slave|failed" check should be changed to " not slave.Is_Slave," or something along those lines, but when then check is skipped (like for a master), that field is not present.

**Comment by geerlingguy** [comment]
@patrickdoc - Hmm... in that case, do you know what version of Ansible this change will make its way into? 2.1.x, 2.2+, etc.?

It's a big enough change that it warrants a major version change for this role, I think, as well as some sort of notification in the README about the change... I don't want people's replication to get broken!

**Comment by patrickdoc** [comment]
I'm not totally sure about how the releases work, but the change has been merged into the "devel" branch of the extras repo. I asked on the irc channel, and was told that, generally, for each ansible release, the submodules are pointed to the head of the "devel" branch.

So the best answer I can offer is the next release. But if you know any more about the release process, I'm certainly willing to do more looking.

**Comment by donat-b** [comment]
I confirm replication is no longer working for Ansible 2.2.0.0

**Comment by wallel** [comment]
I also get this error in Ansible 2.2.0.0:
[geerlingguy.mysql : Check slave replication status.] I got result:
ok: [server_slave_db] => {
    "Is_Slave": false, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "config_file": "/root/.my.cnf", 
            "connect_timeout": 30, 
            "login_host": "localhost", 
            "login_password": null, 
            "login_port": 3306, 
            "login_unix_socket": null, 
            "login_user": null, 
            "master_auto_position": false, 
            "master_connect_retry": null, 
            "master_host": null, 
            "master_log_file": null, 
            "master_log_pos": null, 
            "master_password": null, 
            "master_port": null, 
            "master_ssl": false, 
            "master_ssl_ca": null, 
            "master_ssl_capath": null, 
            "master_ssl_cert": null, 
            "master_ssl_cipher": null, 
            "master_ssl_key": null, 
            "master_user": null, 
            "mode": "getslave", 
            "relay_log_file": null, 
            "relay_log_pos": null, 
            "ssl_ca": null, 
            "ssl_cert": null, 
            "ssl_key": null
        }, 
        "module_name": "mysql_replication"
    }, 

so the condition `slave|failed` always False
