### ISSUE TITLE
Timeout (12s) waiting for privilege escalation prompt

### ISSUE THREAD

**Issue by timbroder** [geerlingguy/ansible-role-mysql#153]
I get this intermittently and haven't been able to nail down why:

```
TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] ***
fatal: [default]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```

Have you seen this before?

Env on Vagrant:
Ubuntu 14.04.4 LTS                          built 2016-04-26

Thanks

**Comment by geerlingguy** [comment]
@timbroder - Typically this indicates the task is not being run as `sudo` or `root`, or that there's a prompt and you aren't running the playbook with the `--ask-sudo-pass` option... are you running the role with `become: yes` in your playbook?

See also: http://stackoverflow.com/a/22201707/100134

**Comment by timbroder** [comment]
I am running as root yes. The weird part is that it's intermittent

**Comment by cggruszka** [comment]
I have become: yes in the role:
`   - { role: geerlingguy.mysql, become: yes, tags: [ 'mysql' ] }`
and run with -K or --ask-sudo-pass to prompt for sudo password.  I've seen this problem once, but it did not repeat in a couple runs since.

> TASK [geerlingguy.mysql : Copy my.cnf global MySQL configuration.] *************
> fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}

**Comment by tofaramac** [comment]
I am as well experiencing the same problem and it just started but i was able to run plays before. Nothing changed please help

**Comment by lesteff** [comment]
had same issue - not sure if its related or general issue. 
I installed various python3 packages via apt - so my default python interpreter has changed. 

when I had to force to use python2:
`python /usr/bin/ansible-playbook site.yml --limit host.nts.ch -K ` -> works fine. 
reproduce with python3 (or just ansible-playbook...)
`python3 /usr/bin/ansible-playbook site.yml --limit host.nts.ch -K ` -> Timeout waiting for privilege escalation prompt

python3 works with limitation when i us paramiko as ssh `-c paramiko`

OS: Ubuntu 16.04.2 LTS
ansible 2.2.1.0 via ppa

**Comment by wyaeld** [comment]
@lesteff I think its a general issue, happening to me intermittently with other roles as well.  Host and guest both Ubuntu 16.04

**Comment by geerlingguy** [comment]
I still have never had this issue, though I'm almost always running the role with an admin account that doesn't have a sudo prompt.

It sounds like this is related to some upstream issue in Ansible itself, possibly having to do with python, ssh connections, and sudo escalation timeouts, so I'd recommend opening an upstream issue asking the same thing in the Ansible repo.

**Comment by geerlingguy** [comment]
I ran into this one time with my Apache role on Ubuntu 16.04 (host was my Mac on 10.12.4). I also found this issue, which seems pertinent: https://github.com/ansible/ansible/issues/14426
