### ISSUE TITLE
Question: AppArmor and log files

### ISSUE THREAD

**Issue by sanegames** [geerlingguy/ansible-role-mysql#154]
The current default setup for the log files is:

    mysql_slow_query_log_file: /var/log/mysql-slow.log
    mysql_log_error: /var/log/mysql.err

When running the role on Ubuntu under AppArmor, mysqld fails to start because `/var/log` is not a valid place for mysqld to write files under the default policy. This is fixed easily by overriding the variables to put the logs in `/var/log/mysql`. Is there a reason why the log files don't default here? I'm curious, because in my debug of this problem it wasn't immediately obvious at first that AppArmor was the culprit. I suspect that others may have this problem as well.

There is a mention of AppArmor in the README in relation to the slow query log, which I did not have enabled. It mentions adding the `/var/log` path to the existing policy, or disabling AppArmor for mysqld. This seems a more involved solution than to place the log files in a directory covered by the current AppArmor policy.

Thanks for any feedback.

**Comment by geerlingguy** [comment]
Fixed via https://github.com/geerlingguy/ansible-role-mysql/pull/135 — you should be able to override the vars now.
