### ISSUE TITLE
Why is there no docker build for Ubuntu?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-mysql#157]
I see that the ubuntu build has been commented out?

* Do you experience issues with 16.04 as well?
* Do you experience [this issue](http://serverfault.com/questions/796105/why-does-the-play-recap-not-work-anymore-while-testing-an-ansible-playbook-on-ub) as well?

**Comment by geerlingguy** [comment]
@030 - There is a 14.04 build currently: https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml#L15-L19

But yeah, I've noticed this weird problem appearing on some Travis builds in the past week (where I get the message `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. The build has been terminated`). It might have to do with Travis' recent infrastructure-wide changes, not quite sure.

**Comment by geerlingguy** [comment]
@030 - I'd suggest an issue in the Travis CI issue queue ([link](https://github.com/travis-ci/travis-ci/issues)); after some searching, I did find https://github.com/travis-ci/travis-ci/issues/6479, but that seems to not be directly related to this Ubuntu-container-running-Ansible-specific issue.

Also, I've had some successful builds in other containers besides this MySQL container using Ansible + Ubuntu 16/14/12 for other projects, so maybe there's something specific about MySQL or something like that...

**Comment by geerlingguy** [comment]
I got things working again by switching back to an earlier version of Docker (which Travis recommends as a workaround until they can get the latest Docker version working correctly for edge cases like running/connecting to MySQL inside a container inside Travis for testing :D).

See:

  - https://github.com/geerlingguy/ansible-role-mysql/pull/159
  - https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-239577306
