### ISSUE TITLE
Security issue storing root password in plaintext

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-role-mysql#162]
It is ironic that in secure-installation.yml you write a plaintext file with the root password.

**Comment by geerlingguy** [comment]
@bbaassssiiee - As long as the file permissions on that file are correct (0400 or 0600), this is a best practice for MySQL server administration (ref: http://security.stackexchange.com/a/72837/18612, http://dev.mysql.com/doc/refman/5.7/en/password-security-user.html)

**Comment by bbaassssiiee** [comment]
Well @geerlingguy it is time to update that practice to use an encrypted store, see: http://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html

**Comment by geerlingguy** [comment]
@bbaassssiiee - Unfortunately, there aren't many tools around the new config editor that work with automation (Ansible, Chef, etc.), so I'm going to postpone any changes until Ansible (or other simple-to-integrate tools that don't add too much complexity to the role) supports the use of the new config file natively.

See: http://docs.ansible.com/ansible/mysql_user_module.html / http://docs.ansible.com/ansible/mysql_variables_module.html

**Comment by geerlingguy** [comment]
@bbaassssiiee - Unfortunately, there aren't many tools around the new config editor that work with automation (Ansible, Chef, etc.), so I'm going to postpone any changes until Ansible (or other simple-to-integrate tools that don't add too much complexity to the role) supports the use of the new config file natively.

See: http://docs.ansible.com/ansible/mysql_user_module.html / http://docs.ansible.com/ansible/mysql_variables_module.html

I'd recommend opening an upstream issue in Ansible's extra modules repo to request support in the official MySQL modules: https://github.com/ansible/ansible-modules-extras

**Comment by bbaassssiiee** [comment]
It turns out that the new file does not add security: https://www.percona.com/blog/2016/09/07/get-passwords-plain-text-mylogin-cnf/
Playbooks can use ansible-vault though.

**Comment by geerlingguy** [comment]
Yeah, sound slike ansible-vault is the best way to handle this, if you need to avoid any password leakage.
