### ISSUE TITLE
MySQL (not mariadb) not installable on Centos 7

### ISSUE THREAD

**Issue by frankdejonge** [geerlingguy/ansible-role-mysql#163]
I'm trying to get MySQL installed on Centos 7. Due to the vars that are set in a way that are not overwritable everything defaults to mariadb settings, causing `touch` actions to fail. Is there a way to work around this? I _did_ see a PR open for this, perhaps that one is worth taking a look at?

**Comment by geerlingguy** [comment]
Fixed via https://github.com/geerlingguy/ansible-role-mysql/pull/135 — you should be able to override the vars now.

**Comment by frankdejonge** [comment]
@geerlingguy awesome, thanks!
