### ISSUE TITLE
[WARNING]: Consider using file module with state=touch rather than running

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-mysql#164]
TASK [geerlingguy.mysql : Create error log file (if configured).] **************

**Comment by glatapoui** [comment]
I have the same warning. Is there some patch already planned ?

**Comment by geerlingguy** [comment]
This was fixed here: https://github.com/geerlingguy/ansible-role-mysql/commit/f45e1a892ce13eeadda434d028915b40db0db29a
