### ISSUE TITLE
replication.yml breaking with latest ansible 2.2.0

### ISSUE THREAD

**Issue by barboni** [geerlingguy/ansible-role-mysql#167]
By simply letting the role run with default variables, I'm getting the following error:

```
ERROR! Undefined delegate_to host for task:

The error appears to have been in '/home/ansible/fc24/roles/geerlingguy.mysql/tasks/replication.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Check master replication status.
  ^ here
```

Currently using ansible/ansible@3c9966d

Quickfix > setting mysql_replication_master: 'localhost'

**Comment by lukasged** [comment]
I can confirm this. I'm using the ansible 2.2.0 rc1 and getting the same error now.

**Comment by geerlingguy** [comment]
@barboni / @lukasged - Hmm... Are you sure `mysql_replication_master` is defined and not empty? The syntax is correct, so if it was working in 2.1 and is broken in 2.2, that sounds like it could be an Ansible core or extras bug.

**Comment by barboni** [comment]
`mysql_replication_master` still has the default value `''`. But I guess this `when`-clause isn't catching anymore: https://github.com/geerlingguy/ansible-role-mysql/blob/6967874c08ae32175195e1a8dd190c812626883e/tasks/replication.yml#L29

Anyhow, I'm pretty sure it worked before without setting `mysql_replication_master` to a non-empty value.

**Comment by PJMODOS** [comment]
See https://github.com/ansible/ansible/pull/17783

**Comment by geerlingguy** [comment]
I forgot to close out this issue—but it should be fixed via https://github.com/geerlingguy/ansible-role-mysql/pull/176

**Comment by geerlingguy** [comment]
@PJMODOS - If there is a separate/related issue (especially if you have a solution), please file a new issue for it. Thanks!
