### ISSUE TITLE
develo

### ISSUE THREAD

**Issue by nicolaasuni** [geerlingguy/ansible-role-mysql#168]

**Comment by geerlingguy** [comment]
@nicolaasuni - Was there anything more to this issue? If you have a particular problem or question, please feel free to edit and I can reopen it.

**Comment by nicolaasuni** [comment]
@geerlingguy I am not sure what happened here as I haven't opened this intentionally. Please discard it.

**Comment by geerlingguy** [comment]
Sounds good!
