### ISSUE TITLE
Ubuntu 14.04.4 fails on "Ensure MySQL is started and enabled on boot"

### ISSUE THREAD

**Issue by pulasthibandara** [geerlingguy/ansible-role-mysql#171]
This error was returned on a Ubuntu/trusty64 box on vagrant

```
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "start: Job failed to start\n"}
```

manually running `sudo service mysql start` worked

**Comment by pulasthibandara** [comment]
I managed to narrow down this issue. The role works perfectly on a 32 bit VM ie: ( ubuntu/trusty32 )
However it fails in ubuntu/trusty64

**Comment by geerlingguy** [comment]
Strange... I haven't encountered the issue on `geerlingguy/ubuntu1404` or the `bento` version, both are 64 bit. I've always encountered very strange issues with the official `ubuntu` Vagrant boxes :/

**Comment by pulasthibandara** [comment]
I was using "ansible_local" provisioner as I was running this on a Windows machine. Will test it with "Ansible" provisioner and let you know

**Comment by pulasthibandara** [comment]
It seems the issue only happens when used with "ansible_local" vagrant provisioner.

**Comment by lianghuiyuan** [comment]
Ubuntu14.04: 
> TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
task path: /Volumes/creasy/gitlab/deployment/roles/external/geerlingguy.mysql/tasks/configure.yml:67
<testjumper> ESTABLISH SSH CONNECTION FOR USER: root
<testjumper> SSH: EXEC sshpass -d50 ssh -C -q -i ../ssh_keys/aliyun.key -F ../ssh.config -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 testjumper '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651 `" && echo ansible-tmp-1481784744.22-41102284651651="` echo $HOME/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651 `" ) && sleep 0'"'"''
<testjumper> PUT /var/folders/y1/4fnv5_mn4bq73b4kvzs4td840000gn/T/tmpNv4V1Y TO /root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/service
<testjumper> SSH: EXEC sshpass -d50 scp -C -i ../ssh_keys/aliyun.key -F ../ssh.config -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 /var/folders/y1/4fnv5_mn4bq73b4kvzs4td840000gn/T/tmpNv4V1Y '[testjumper]:/root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/service'
<testjumper> ESTABLISH SSH CONNECTION FOR USER: root
<testjumper> SSH: EXEC sshpass -d50 ssh -C -q -i ../ssh_keys/aliyun.key -F ../ssh.config -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 testjumper '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/ /root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/service && sleep 0'"'"''
<testjumper> ESTABLISH SSH CONNECTION FOR USER: root
<testjumper> SSH: EXEC sshpass -d50 ssh -C -q -i ../ssh_keys/aliyun.key -F ../ssh.config -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -tt testjumper '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/service; rm -rf "/root/.ansible/tmp/ansible-tmp-1481784744.22-41102284651651/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [testjumper]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "mysql", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "msg": "Error when trying to enable mysql: rc=1 Failed to issue method call: No such file or directory\n"}
NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Volumes/creasy/gitlab/deployment/plays/dbs.retry

**Comment by peterver** [comment]
I encountered the same issue, after ssh'ing into vagrant i and manually running the following : 

```
sudo service mysql start && sudo find / -type s | grep mysqld.sock
```

I noticed that the mysql socket was located at /run/mysqld/mysqld.sock instead of /var/run/... 

Using ansible_local as a provisioner

**Comment by geerlingguy** [comment]
@peterver - Thanks for posting that! It seems that it could be related to how the role functions when run with a local connection vs via SSH. Also consider that using `ansible_local` _might_ mean that the role is run with a newer (or older) version of Ansible than the one you might have installed on your host.

In any case, usually when things fail during a `service` module task, the best way to debug is to log into the server and try manually, and see if there's a failure.

I'm going to close this for now, but please let me know if you're still having trouble, and if you can think of a way we could get it to work better.
