### ISSUE TITLE
root .my.cnf won't update after mysql_root_password has changed

### ISSUE THREAD

**Issue by senorsmile** [geerlingguy/ansible-role-mysql#178]
Here's the specific scenario that I ran into: 

- I moved a file in group_vars that made them not apply to the server properly
- I ran ansible against the node, which changed the password in /root/.my.cnf from the actual root mysql password to the default 'root' from the role's defaults/main.yml
- I ran ansible again and get a failure at 
  - 
``` 
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
task path: /var/lib/jenkins/workspace/ansible-docker/roles/geerlingguy.mysql/tasks/secure-installation.yml:2
failed: [icinga-server] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.004201", "end": "2016-11-08 22:06:31.254759", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-11-08 22:06:31.250558", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)", "stdout": "", "stdout_lines": [], "warnings": []} 
```
- I saw the problem and then moved the yml file to the proper place in group_vars
- I verified with a debug message that the mysql_root_password was properly set now
- Running ansible again never gets to the code to update the .my.cnf, because that task is AFTER the above task that errs out.  

Since the current order of things has to do with idempotence as stated here:
```yaml
# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mysql_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
```
it's unclear what  a good solution would be for this scenario.  

I was able to get around it by copying that task, putting a temporary copy of the above task before the root .my.cnf task, and later removed it.  This allowed everything to run as expected.

**Comment by guimaluf** [comment]
I'm also experiencing this error. 
How I'm using this role
```
- name: Install MySQL
  include_role:
    name: "geerlingguy.mysql"
  vars:
    mysql_user_home: "{{ lemonade_system_user_home }}"
    mysql_databases:
      - name: thorn
    mysql_users:
      - name: "{{ lemonade_thorn_db_user }}"
        host: "%"
        password: "{{ lemonade_thorn_db_passwd }}"
        priv: "{{ lemonade_thorn_db_user }}.*:ALL"
    mysql_root_password_update: yes
    mysql_root_password: super-secure-password
```

**Comment by ccjjmartin** [comment]
This PR solves the issue:
https://github.com/geerlingguy/ansible-role-mysql/pull/185

**Comment by abelboldu** [comment]
I'm having this issue on a vanilla trusty image of travis ci:

https://travis-ci.org/abelboldu/ansible-midonet-gateway/jobs/183537704

**Comment by geerlingguy** [comment]
Closing to consolidate discussion in https://github.com/geerlingguy/ansible-role-mysql/issues/57
