### ISSUE TITLE
always_run is deprecated

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-mysql#179]
```
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```

**Comment by geerlingguy** [comment]
The problem is if I switch to `check_mode == no`, then I'll end up requiring everyone update to Ansible 2.2 (because that variable doesn't work in < 2.2). So I'm going to close this and hold off on updating my roles until sometime around when 2.3 comes out.
