### ISSUE TITLE
Remove anonymous MySQL user fails

### ISSUE THREAD

**Issue by wroxbox** [geerlingguy/ansible-role-mysql#18]
TASK: [geerlingguy.mysql | Remove anonymous MySQL user.] **********************
failed: [drupaldev] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

FATAL: all hosts have already failed -- aborting

**Comment by geerlingguy** [comment]
@wroxbox - Are you still having this issue? I haven't been able to reproduce with fresh installs on any of the following:

  - Ubuntu 12.04
  - Ubuntu 14.04
  - CentOS 6
  - CentOS 7

**Comment by geerlingguy** [comment]
This role has seen a bunch of changes in the past couple months making it a bit more stable/correct in dealing with the initial account setup (adjusting root and removing the anonymous user). I'm closing this issue for now, please open a new ticket if you can reproduce again (and please include system info so it's easier for me to try reproducing).
