### ISSUE TITLE
master-master replication?

### ISSUE THREAD

**Issue by dgptamayo** [geerlingguy/ansible-role-mysql#181]
Hi. Looking at the conditions used in `replication.yml`, seems like master-master replication isn't possible to configure. Is it supported? Thanks.

**Comment by geerlingguy** [comment]
Not at this time; but it would be something I'd be happy to accept patches for. I only use replication for a few of my projects, and always as master-slave, so it hasn't been a priority for me.

**Comment by geerlingguy** [comment]
I'm going to close this ticket for now—since this role is aiming for simplicity over completeness, I don't think I can support master-master right now.
