### ISSUE TITLE
users.yml task breaks against mysql 8.0 dmr

### ISSUE THREAD

**Issue by killua-eu** [geerlingguy/ansible-role-mysql#189]
##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Ubnutu, current 16.04.1 LTS 

##### SUMMARY
The task failed, so after commenting out the "no_log: true" line, I got

```
failed: [killua] (item={u'host': u'127.0.0.1', u'password': u'secretpw', u'name': u'killua', u'priv': u'*.*:ALL'}) => {"failed": true, "item": {"host": "127.0.0.1", "name": "killua", "password": "secretpw", "priv": "*.*:ALL"}, "msg": "unable to parse the MySQL grant string: GRANT ALL PRIVILEGES ON *.* TO `killua`@`127.0.0.1`"}
```

Everything works just fine against mysql 5.7. 

-vvvv run:

```
ailed: [killua] (item={u'host': u'127.0.0.1', u'password': u'secretpw', u'name': u'killua', u'priv': u'*.*:ALL'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "append_privs": false, 
            "check_implicit_admin": false, 
            "config_file": "/root/.my.cnf", 
            "connect_timeout": 30, 
            "encrypted": false, 
            "host": "127.0.0.1", 
            "host_all": false, 
            "login_host": "localhost", 
            "login_password": null, 
            "login_port": 3306, 
            "login_unix_socket": null, 
            "login_user": null, 
            "name": "killua", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "priv": "*.*:ALL", 
            "sql_log_bin": true, 
            "ssl_ca": null, 
            "ssl_cert": null, 
            "ssl_key": null, 
            "state": "present", 
            "update_password": "always", 
            "user": "killua"
        }, 
        "module_name": "mysql_user"
    }, 
    "item": {
        "host": "127.0.0.1", 
        "name": "killua", 
        "password": "secretpw
        "priv": "*.*:ALL"
    }, 
    "msg": "unable to parse the MySQL grant string: GRANT ALL PRIVILEGES ON *.* TO `killua`@`127.0.0.1`"
}
```

**Comment by geerlingguy** [comment]
@killua-eu - I haven't yet started working on porting this role to work with MySQL 8.x—and I likely won't take the time until it's been stable for a month or two at least :)

A lot of things around auth have changed, and the Ansible modules themselves might take some time to get updated to support 8.x as well.

If you can find any quick fixes that'd be awesome, but I'm guessing this is not the only thing that will break.

**Comment by killua-eu** [comment]
@geerlingguy its really the ansible modules lacking. I hit a problem only with auth, but truth be told I didn't check everything. Quick fix might be an ugly hack. Would you be willing to include that into the codebase as a temp solution, or better wait it out?

**Comment by geerlingguy** [comment]
If you can find a backwards-compatible quick fix (and make sure to comment it as such) for a PR, I would be willing to accept it. But I generally wait to support releases until they're final/stable (just because they're always moving targets).

**Comment by geerlingguy** [comment]
I'm going to wait it out on this one; since few ansible users are currently testing out the latest MySQL versions, I've found it difficult to get upstream support when necessary on any non-stable release.

**Comment by ctessmer** [comment]
👍 for a port to mysql 8.x in 2018.

_PS: Thank you, btw, @geerlingguy! My Ansible-provisined, up-to-date LEMP server would not be reality without your amazing roles.)_

**Comment by dreamcatcha** [comment]
How are we going for mysql 8.x support for the users?

**Comment by sebstyle** [comment]
If you don't mind the task registering as changed every time the role runs..
```
mysql_users:
  - name: myuser
    password: "mypassword"
    state: absent
    priv: "mydb.*:ALL"
  - name: myuser
    password: "mypassword"
    state: present
    priv: "mydb.*:ALL"
```
I know, it's not a fix, just wanted to share how to temporarily get the role running every time for the people that want to play around a bit with version 8.0 until all parties involved get things fixed.

**Comment by styks1987** [comment]
@sebstyle temp fix worked for me.

**Comment by luirro777** [comment]
@sebstyle I tried that, but now ansible shows a syntax yaml error.
I validated the file at codebeautify. So, I don't understand why ansible says that.
