### ISSUE TITLE
Root password never applied

### ISSUE THREAD

**Issue by LeonardoGentile** [geerlingguy/ansible-role-mysql#196]
I've tried multiple times but it seems that these settings have no effect:
```
mysql_root_password_update: yes
mysql_root_password: whatever
```
When reaching these two blocks in secure-installation.yml
```
# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (>=5.7.x).
  shell: >
    mysql -u root -NBe
    'ALTER USER "{{ mysql_root_username }}"@"{{ item }}" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: ((mysql_install_packages | bool) or mysql_root_password_update) and ('5.7.' in mysql_cli_version.stdout)

# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  shell: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: ((mysql_install_packages | bool) or mysql_root_password_update) and ('5.7.' not in mysql_cli_version.stdout)
```
in my case only the first one will be executed given that I've installed `Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper`.

On the log I can see: 
```
TASK [mysql : Update MySQL root password for localhost root account (>=5.7.x).]
changed: [digitalocean] => (item=localhost)
```
So I assumed it worked as expected but it's never the case.
I tried to connect with the user root and it only works by passing the standard root password "root" not the one I've set in `mysql_root_password`.

I've tried to run manually 
```
 mysql -u root -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH "root" BY "my_new_pass";'
```
with all possible combination with and without quotes for passwords and host. It complaints, saying that 
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

What am I missing here?

**Comment by frostymarvelous** [comment]
I just wasted hours trying and trying and trying to get this to work. 
Had to manually put in a password

**Comment by geerlingguy** [comment]
I just verified that the functionality is working as expected—at least as long as you've used this role, and only this role, to manage the password. If not, you need to make sure that the root user account has a `~/.my.cnf` file with the current `[client]` root user and password settings, then you can use the role to update the root password.

Here's how I tested to verify (tests done on Ubuntu 14 and 16; didn't re-check manually on CentOS 6/7):

Build a Docker container using the test rig (assuming you have Docker installed and are in this repository's root directory):

  1. `wget -O tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/`
  2. `chmod +x tests/test.sh`
  3. `distro=ubuntu1604 playbook=test.yml container_id=1234 cleanup=false
 ./tests/test.sh`

Verify that the default `root` password (`root`) works:

```
$ docker exec 1234 mysql -u root -proot -e "show databases;"
Database
information_schema
mysql
performance_schema
sys
mysql: [Warning] Using a password on the command line interface can be insecure.
```

Set the following two variables to change the root password inside of `test.yml`:

```yaml
  vars:
    mysql_root_password: test
    mysql_root_password_update: yes
```

Run the test playbook again inside the container:

  * `$ docker exec 1234 ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml`

Verify that the old root password (`root`) no longer works:

```
$ docker exec 1234 mysql -u root -proot -e "show databases;"
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Verify that the new password (`test`) is being used:

```
$ docker exec 1234 mysql -u root -ptest -e "show databases;"
Database
information_schema
mysql
performance_schema
sys
mysql: [Warning] Using a password on the command line interface can be insecure.
```

**Comment by ytjohn** [comment]
@LeonardoGentile @frostymarvelous were you using sudo to run ansible-playbook?  If so, can you try either without sudo or `sudo -H` to pass in the correct $HOME variable?

**Comment by ggCS** [comment]
Is there a way to do this without docket?

**Comment by geerlingguy** [comment]
@ggCS - You mean run playbooks using this role without using Docker?

I'm currently using it for Drupal VM (a Vagrant VM building tool), on a large variety of servers (LAMP stack, SonarQube with MySQL backend, a custom Node.js app with a MySQL backend, etc.), and have no issues setting and/or changing the root password using this role's built-in functionality. I've tested it on systems running Ubuntu 14.04, 16.04, and CentOS 7 personally.

**Comment by JHeimbach** [comment]
I came across the same problem, no matter what i couldnt login with root and the provided password (self set or default from this role)

I could fix it with this https://askubuntu.com/a/964762, maybe that is the underlying problem and therefore it is only reproducible with ubuntu 16.04

**Comment by zhang-hy-2016** [comment]
I got the same issue in my recent project. I find the problem maybe is  [here](https://github.com/geerlingguy/ansible-role-mysql/blob/bf83308f9d125298dec810efc036b8f6e1ba884a/tasks/secure-installation.yml#L23)  

` ` ` 
- name: Copy user-my.cnf file with password credentials.
  ... 
  when: mysql_user_name != mysql_root_username and (mysql_install_packages | bool or mysql_user_password_update)
` ` ` 

I start at a Ubuntu , xenial + 16.04 server which never run with role before , but with a pre-installed mysql.  If only set the `mysql_root_password` , the copy file task is skipped and then the play-book stopped at next DB operation, because there is no `.my.cnf` at `/root`.   

I like this role, so my solution is remove `mysql_user_name != mysql_root_username` check, ensure `.my.cnf` is existed so that the script always have chance to login at DB.  If I want to update existed root password,  I set the parameter with:

`
    mysql_root_home: /root
    mysql_root_username: root
    mysql_root_password: newpasswd
    mysql_user_home: /root
    mysql_user_name: root
    mysql_user_password: oldpass
`

The new code 
`
  when: (mysql_install_packages | bool )
`

**Comment by mabushey** [comment]
This problem exists on Ubuntu bionic.

**Comment by ctessmer** [comment]
@mabushey Same here. I'm seeing this on Ubuntu 18.04 bionic.

**Comment by geerlingguy** [comment]
I just tested with Bionic (finally had time to add a test for it in CI), and it seems to be working okay: https://travis-ci.org/geerlingguy/ansible-role-mysql/jobs/445179879

I do seem to have an issue with Debian 9, however, at least in CI environments. See related: https://github.com/geerlingguy/ansible-role-mysql/issues/57

**Comment by cdarken** [comment]
I don't think setting the password for root user on Ubuntu 18.04 works, because they changed the authentication plugin for root, from mysql_native_password to auth_socket.

**Comment by tgadiev** [comment]
Don't use hardcoded command called by this role. MySQL native root credentials reset procedure is performed by restarting MySQL in `skip-grant-tables` mode. Using this approach root password can be reset and set to a new custom value.

**Comment by cdarken** [comment]
@tgadiev I'm not sure I understand what you're trying to say.
The root password can be set with the following steps:
1. start mysql client as root
2. switch to mysql database
3. execute this: 
```
update users set plugin = 'mysql_native_password` where User = 'root';
flush privileges;
set password for 'root'@'localhost' = 'clean_text_password';
```
I'm not sure if these steps can be reproduced in ansible, but it could be useful to have them available and inactive by default, only activated by a flag.

**Comment by tgadiev** [comment]
@cdarken you can take a look at this role for example:
https://github.com/lean-delivery/ansible-role-mysql

We tested it for all modern distributions and MySQL versions. It performs password reset by native mysql modules.

**Comment by colinleefish** [comment]
> @cdarken you can take a look at this role for example:
> https://github.com/lean-delivery/ansible-role-mysql
> 
> We tested it for all modern distributions and MySQL versions. It performs password reset by native mysql modules.

Your workaround solution works. Thanks man!

**Comment by skuark** [comment]
@cdarken Your solution works for me also. Thanks!

**Comment by cdarken** [comment]
@tgadiev @colinleefish @skuark  take a look at this line: https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/secure-installation.yml#L42

So you either have to set `mysql_root_password_update` to `true` or the mysql packages have to be installed when running the role.
In my case I believe I already had mysql installed and I didn't set `mysql_root_password_update`, that's why I had to run the queries above manually.
