### ISSUE TITLE
Multi slave replication example

### ISSUE THREAD

**Issue by Royce92** [geerlingguy/ansible-role-mysql#198]
Can anyone provide me with a multi slave replication example. The configuration thinks all the servers are master and theirs a binding conflict. 

The instructions aren't clear enough.

**Comment by zx1986** [comment]
I got error in replication.yml: 

```
master_log_file: "{{ master.File }}"
master_log_pos: "{{ master.Position }}"
```

There are no master variable attributes about File and Position.

**Comment by jiming** [comment]
+1

**Comment by sfblaauw** [comment]
+1

**Comment by MariusHerget** [comment]
+1

**Comment by LandonStewart** [comment]
+1

**Comment by PrestanceDesign** [comment]
#245

**Comment by roedie** [comment]
Would be nice if this one was merged.

**Comment by Maelstromeous** [comment]
+1
