### ISSUE TITLE
Access denied: Quoting password in .my.cnf file

### ISSUE THREAD

**Issue by nienaber** [geerlingguy/ansible-role-mysql#200]
Hello, 

I got the following error:
```
TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in
 version 2.4. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [45.56.117.147]: FAILED! => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.006273", "end": "2017-02-09 21:38:34.740039", "failed": true, "rc": 1, "start": "2017-02-09 21:38:34.733766", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)", "stdout": "", "stdout_lines": [], "warnings": 
```
The issue can be resolved by editing the `/root/.my.cnf` file and quoting the password:

```
[client]
user=root
password="password-here"
```

Additionally if the password contains an equal sign this will cause an error when the password is not quoted:

```
[client]
user=root
password=password=here
```

**Comment by geerlingguy** [comment]
Thanks for reporting this; I verified that the quoting should fix this issue. Note that doing this might also cause issues with any password using the quote (`"`) character as _part of the password_ itself. But as this is often an issue with passwords in any standard circumstance, I don't think that warrants doing any more processing to the password as passed into this template.
