### ISSUE TITLE
Possibility to change group_concat_max_len in my.cnf

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-mysql#206]
https://github.com/geerlingguy/ansible-role-mysql/blob/master/templates/my.cnf.j2#L6

http://serverfault.com/a/347079/215599

In the default main it is possible to set some MySQL parameters: https://github.com/geerlingguy/ansible-role-mysql/blob/master/defaults/main.yml#L53

The group_concat_max_len is omitted. Could this be added?

**Comment by surudoiryu** [comment]
Would be handy for me too,being able to change this.
Got some JSON output's that needs this to be set to atleast 60000

**Comment by geerlingguy** [comment]
Merged and fixed!
