### ISSUE TITLE
Possibility for adding join_buffer_size

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-mysql#207]
The same as #206, but a different parameter

**Comment by geerlingguy** [comment]
For both of these issues, would you be able to submit a PR with the requested changes?

**Comment by geerlingguy** [comment]
Merged and fixed!

**Comment by 030** [comment]
@geerlingguy Thank you! When will a new release be published to galaxy?

**Comment by geerlingguy** [comment]
I will need to get tests passing again prior to another release.

**Comment by geerlingguy** [comment]
Hopefully later today though.
