### ISSUE TITLE
Unable to start service mysqld: Job for mysqld.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by JamesYuan** [geerlingguy/ansible-role-mysql#215]
Hi,

geerlingguy.mysql, version: 2.7.0

OS:
CentOS Linux release 7.2.1511 (Core)

Error:

```
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [172.16.51.147]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service mysqld: Job for mysqld.service failed because a timeout was exceeded. See \"systemctl status mysqld.service\" and \"journalctl -xe\" for details.\n"}
```

journalctl -xe:

```
Apr 15 05:15:16 bogon mysqld_safe[6207]: 170415 05:15:16 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
Apr 15 05:15:16 bogon mysqld_safe[6207]: /usr/bin/mysqld_safe: line 136: /var/log/mysqld.err: Permission denied
Apr 15 05:15:16 bogon systemd[1]: mysqld.service: main process exited, code=exited, status=1/FAILURE
Apr 15 05:16:16 bogon sshd[3288]: Received disconnect from 10.242.3.2: 11: disconnected by user
Apr 15 05:16:16 bogon sshd[3288]: pam_unix(sshd:session): session closed for user root
Apr 15 05:16:16 bogon systemd-logind[652]: Removed session 6.
-- Subject: Session 6 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 6 has been terminated.
lines 2624-2662/2662 (END)
Apr 15 05:05:16 bogon mysqld_safe[3865]: /usr/bin/mysqld_safe: line 181: /var/log/mysqld.err: Permission denied
Apr 15 05:05:16 bogon mysqld_safe[3865]: 170415 05:05:16 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
Apr 15 05:05:16 bogon mysqld_safe[3865]: /usr/bin/mysqld_safe: line 136: /var/log/mysqld.err: Permission denied
Apr 15 05:05:16 bogon systemd[1]: mysqld.service: main process exited, code=exited, status=1/FAILURE
Apr 15 05:15:16 bogon systemd[1]: mysqld.service start-post operation timed out. Stopping.
Apr 15 05:15:16 bogon systemd[1]: Failed to start MySQL Community Server.
-- Subject: Unit mysqld.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mysqld.service has failed.
--
-- The result is failed.
Apr 15 05:15:16 bogon systemd[1]: Unit mysqld.service entered failed state.
Apr 15 05:15:16 bogon systemd[1]: mysqld.service failed.
Apr 15 05:15:16 bogon systemd[1]: mysqld.service holdoff time over, scheduling restart.
Apr 15 05:15:16 bogon systemd[1]: Starting MySQL Community Server...
-- Subject: Unit mysqld.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mysqld.service has begun starting up.

Apr 15 05:15:16 bogon mysqld_safe[6207]: 170415 05:15:16 mysqld_safe Logging to '/var/log/mysqld.err'.
Apr 15 05:15:16 bogon mysqld_safe[6207]: /usr/bin/mysqld_safe: line 136: /var/log/mysqld.err: Permission denied
Apr 15 05:15:16 bogon mysqld_safe[6207]: 170415 05:15:16 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
Apr 15 05:15:16 bogon mysqld_safe[6207]: /usr/bin/mysqld_safe: line 136: /var/log/mysqld.err: Permission denied
Apr 15 05:15:16 bogon mysqld_safe[6207]: /usr/bin/mysqld_safe: line 181: /var/log/mysqld.err: Permission denied
Apr 15 05:15:16 bogon mysqld_safe[6207]: 170415 05:15:16 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
Apr 15 05:15:16 bogon mysqld_safe[6207]: /usr/bin/mysqld_safe: line 136: /var/log/mysqld.err: Permission denied
Apr 15 05:15:16 bogon systemd[1]: mysqld.service: main process exited, code=exited, status=1/FAILURE
Apr 15 05:16:16 bogon sshd[3288]: Received disconnect from 10.242.3.2: 11: disconnected by user
Apr 15 05:16:16 bogon sshd[3288]: pam_unix(sshd:session): session closed for user root
Apr 15 05:16:16 bogon systemd-logind[652]: Removed session 6.
-- Subject: Session 6 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 6 has been terminated.
~
```

Thanks,
James

**Comment by geerlingguy** [comment]
@JamesYuan - It looks like the error message is:

```
/var/log/mysqld.err: Permission denied
```

When you ran this role initially, did you set the playbook to use `become: yes` so it runs as sudo? If so,  that file seems like it should've been generated for you.

Otherwise, you need to override the `mysql_log_error` configuration variable to set a path to a location on the disk where you'd be able to write.

See the defaults in the Debian/Ubuntu OS here: https://github.com/geerlingguy/ansible-role-mysql/blob/master/vars/Debian.yml

**Comment by geerlingguy** [comment]
Ah, just noticed you're on CentOS. In that case—here are the defaults: https://github.com/geerlingguy/ansible-role-mysql/blob/master/vars/RedHat-7.yml#L10

It seems that you might be trying to install MySQL instead of MariaDB, is that correct?

**Comment by JamesYuan** [comment]
yes, I am trying install MySQL instead of MariaDB.

I tried with the ansible_ssh_user=root, and then add become: yes in the play book. The issue is still there.

After fail, I check the permissions and seems okay?

[root@bogon ~]# ls -lh /var/log/mysql*
-rw-r-----. 1 mysql mysql 3.5K Apr 15 04:35 /var/log/mysqld.err
-rw-r-----. 1 mysql mysql    0 Apr 15 04:35 /var/log/mysqld.log

Here is the pre_tasks from the galaxy and thank you for helping.

https://galaxy.ansible.com/geerlingguy/mysql/
 pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"
  
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"

**Comment by JamesYuan** [comment]
Add a command `whoami` before the Ensure MySQL is started and enabled on boot.

``
TASK [geerlingguy.mysql : debug] ***********************************************
ok: [172.16.51.147] => {
    "whoiam": {
        "changed": true,
        "cmd": [
            "whoami"
        ],
        "delta": "0:00:00.008357",
        "end": "2017-04-15 05:04:30.470921",
        "rc": 0,
        "start": "2017-04-15 05:04:30.462564",
        "stderr": "",
        "stdout": "root",
        "stdout_lines": [
            "root"
        ],
        "warnings": []
    }
}
``

**Comment by geerlingguy** [comment]
@JamesYuan - Ah, one thing it definitely could be: if MariaDB was ever installed previously, that file could be a symlink (see [remove /var/log/mysqld.log](http://stackoverflow.com/a/30201146)).

So try doing `sudo rm -f /var/log/mysqld.err` then try again and see if it works.

**Comment by JamesYuan** [comment]
@geerlingguy - the server is clean installed by CentOS mini installation. There is no MariaDB.

**Comment by geerlingguy** [comment]
@JamesYuan Still, if you run the command above (remove that err log), does the role work?

**Comment by JamesYuan** [comment]
Still error.
`
[root@bogon ~]# rm -f /var/log/mysqld.err
`

`
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [172.16.51.148]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service mysqld: Job for mysqld.service failed because a timeout was exceeded. See \"systemctl status mysqld.service\" and \"journalctl -xe\" for details.\n"}
	to retry, use: --limit @/Users/jyuan/projects/appnestplus/anp_server_ansible/plays/dbservers.retry
`

**Comment by JamesYuan** [comment]
Have to leave the mysql_log_error empty, it solved.

```
  pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"
  
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server']
        mysql_log_error: ""
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
```

**Comment by geerlingguy** [comment]
Strange; If it works, it works, though! At some point I'm considering making the use of the official repo an option in this role, too.

**Comment by JamesYuan** [comment]
@geerlingguy , this is a workaround. 

```
- name: Change context on error log file  (if configured).
  command: chcon system_u:object_r:mysqld_log_t:s0 "{{ mysql_log_error }}"
```

https://bugzilla.redhat.com/show_bug.cgi?id=1066112

Thanks,
James.

**Comment by sizwan** [comment]
Reinstalling MySQL might help:
First uninstall
the remove /var/lib/mysql and /etc/mycnf or /etc/mycng.rpmsave
Reboot the machine
Now install.

**Comment by thatsaru** [comment]
This maybe related to selinux being set to enforcing. Have a look at /etc/selinux/config (on CentOS, location may vary on other distributions). If SELINUX=enforcing, try setting SELINUX=permissive and

- Reboot the machine
- Start MySQL

In case SELINUX=enforcing is required, have a look at https://www.techrepublic.com/blog/linux-and-open-source/practical-selinux-for-the-beginner-contexts-and-labels/ or other similar posts.

Hope this helps.

**Comment by panaceya** [comment]
> This maybe related to selinux being set to enforcing. Have a look at /etc/selinux/config (on CentOS, location may vary on other distributions). If SELINUX=enforcing, try setting SELINUX=permissive and
> 
>     * Reboot the machine
> 
>     * Start MySQL
> 
> 
> In case SELINUX=enforcing is required, have a look at https://www.techrepublic.com/blog/linux-and-open-source/practical-selinux-for-the-beginner-contexts-and-labels/ or other similar posts.
> 
> Hope this helps.

Please don’t disable SeLinux, it MUST be configured.
