### ISSUE TITLE
Centos 7: won't start - ib_logfile size issue

### ISSUE THREAD

**Issue by slarti-b** [geerlingguy/ansible-role-mysql#216]
Trying to use this to do a secure isntall on Centos 7.  I installed the following via the yum task:
    - mariadb-server 
    - mariadb
    - mariadb-libs
    - MySQL-python
    - perl-DBD-MySQL

Then I included this via include_role (minimal variables to set a root password and add a single user).  Worked as far as re-starting the mariadb server, which failed.  The /var/log/mariadb/mariadb.log looks like this:

```
170418 03:28:11 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
170418  3:28:11 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as process 14623 ...
170418  3:28:11 InnoDB: The InnoDB memory heap is disabled
170418  3:28:11 InnoDB: Mutexes and rw_locks use GCC atomic builtins
170418  3:28:11 InnoDB: Compressed tables use zlib 1.2.7
170418  3:28:11 InnoDB: Using Linux native AIO
170418  3:28:11 InnoDB: Initializing buffer pool, size = 128.0M
170418  3:28:11 InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
170418  3:28:11  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
170418  3:28:11  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
170418  3:28:11  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: 127 rollback segment(s) active.
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
170418  3:28:11  InnoDB: Waiting for the background threads to start
170418  3:28:12 Percona XtraDB (http://www.percona.com) 5.5.49-MariaDB-38.0 started; log sequence number 0
170418  3:28:12 [Note] Plugin 'FEEDBACK' is disabled.
170418  3:28:12 [Note] Server socket created on IP: '0.0.0.0'.
170418  3:28:12 [Note] Event Scheduler: Loaded 0 events
170418  3:28:12 [Note] /usr/libexec/mysqld: ready for connections.
Version: '5.5.52-MariaDB'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MariaDB Server
170418  3:28:40 [Note] /usr/libexec/mysqld: Normal shutdown

170418  3:28:40 [Note] Event Scheduler: Purging the queue. 0 events
170418  3:28:40  InnoDB: Starting shutdown...
170418  3:28:41  InnoDB: Shutdown completed; log sequence number 1597945
170418  3:28:41 [Note] /usr/libexec/mysqld: Shutdown complete

170418 03:28:41 mysqld_safe mysqld from pid file /var/run/mariadb/mariadb.pid ended
170418 03:28:41 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
170418  3:28:41 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as process 16527 ...
170418  3:28:41 InnoDB: The InnoDB memory heap is disabled
170418  3:28:41 InnoDB: Mutexes and rw_locks use GCC atomic builtins
170418  3:28:41 InnoDB: Compressed tables use zlib 1.2.7
170418  3:28:41 InnoDB: Using Linux native AIO
170418  3:28:41 InnoDB: Initializing buffer pool, size = 256.0M
170418  3:28:41 InnoDB: Completed initialization of buffer pool
InnoDB: Error: log file ./ib_logfile0 is of different size 0 5242880 bytes
InnoDB: than specified in the .cnf file 0 67108864 bytes!
InnoDB: Possible causes for this error:
 (a) Incorrect log file is used or log file size is changed
 (b) In case default size is used this log file is from 10.0
 (c) Log file is corrupted or there was not enough disk space
 In case (b) you need to set innodb_log_file_size = 48M
170418  3:28:41 [ERROR] Plugin 'InnoDB' init function returned error.
170418  3:28:41 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
170418  3:28:41 [Note] Plugin 'FEEDBACK' is disabled.
170418  3:28:41 [ERROR] Unknown/unsupported storage engine: InnoDB
170418  3:28:41 [ERROR] Aborting

170418  3:28:41 [Note] /usr/libexec/mysqld: Shutdown complete

170418 03:28:42 mysqld_safe mysqld from pid file /var/run/mariadb/mariadb.pid ended
```

I noticed that I had started the server (and apache, and a couple of others) after installation before calling this role.  If I move the service start to after this role, it works fine.  It looks like the first start-up creates the log files, and then the sizes don't match.

As I said, it works for me if I'm super-careful about the order - but is it the idea that you can't run this to make changes to the innodb settings like this in my.cnf?  Shouldn't the role handle dealing with the log files?  The general advice seems to be shutdown the server then delete the log files before re-sizing.  Still googling to see how safe that would be in practice...

**Comment by eythian** [comment]
Seeing the same thing on a Debian 8.8 server.

**Comment by jmrojas01** [comment]
Delete the ib_logfile *, but now I have this error:

8092110:00:21 [Note] mysqld (mysqld 10.0.21-MariaDB-log) starting as process 24443 ...
180921 10:00:21 [Note] InnoDB: Using mutexes to ref count buffer pool pages
180921 10:00:21 [Note] InnoDB: The InnoDB memory heap is disabled
180921 10:00:21 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
180921 10:00:21 [Note] InnoDB: Memory barrier is not used
180921 10:00:21 [Note] InnoDB: Compressed tables use zlib 1.2.3
180921 10:00:21 [Note] InnoDB: Using Linux native AIO
180921 10:00:21 [Note] InnoDB: Using CPU crc32 instructions
180921 10:00:21 [Note] InnoDB: Initializing buffer pool, size = 128.0M
180921 10:00:21 [Note] InnoDB: Completed initialization of buffer pool
180921 10:00:21 [Note] InnoDB: Setting log file ./ib_logfile101 size to 256 MB
InnoDB: Progress in MB:2018-09-21 10:00:21 7f758f454820 InnoDB: Error: Write to file ./ib_logfile101 failed at offset 0.
InnoDB: 1048576 bytes should have been written, only 143360 were written.
InnoDB: Operating system error number 28.
InnoDB: Check that your OS and file system support files of this size.
InnoDB: Check also that the disk is not full or a disk quota exceeded.
InnoDB: Error number 28 means 'No space left on device'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/operating-system-error-codes.html
180921 10:00:21 [ERROR] InnoDB: Cannot set log file ./ib_logfile101 to size 256 MB
180921 10:00:21 [ERROR] Plugin 'InnoDB' init function returned error.
180921 10:00:21 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
180921 10:00:21 [Note] Plugin 'FEEDBACK' is disabled.
180921 10:00:21 [ERROR] Unknown/unsupported storage engine: InnoDB
180921 10:00:21 [ERROR] Aborting

180921 10:00:21 [Note] mysqld: Shutdown complete
