### ISSUE TITLE
Use mysql password hash instead of plaintext

### ISSUE THREAD

**Issue by runtman** [geerlingguy/ansible-role-mysql#219]
This isn't really an issue but I don't see a method to ask a question.

Is adding passwords via the password hash ever on the agenda?

As in this format "*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29", I can see the reason it doesn't work is because the code uses the password("password") function, I was curious if you could add a flag for mysql_password_hash perhaps?

Thanks.

**Comment by geerlingguy** [comment]
The way it is now works for me, because it's the only way I've handled MySQL passwords in the past... but by no means would I say it's the only way I would support.

If you can find a way to add support I'd be willing to take a look.

**Comment by runtman** [comment]
Thanks for the fast response, so normally to avoid passing clear text I would get the mysql password either via a tool or a local instance of mysql:

```
mysql> select password("test");
+-------------------------------------------+
| password("test")                          |
+-------------------------------------------+
| *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |
+-------------------------------------------+
1 row in set (0.00 sec)
```

Then with the hash I would create a user like so:


`| GRANT USAGE ON *.* TO 'phpmyadmin'@'localhost' IDENTIFIED BY PASSWORD '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29' |`

So I could just add the hashes into my puppet / ansible set up, without ever passing the real password.

**Comment by TvL2386** [comment]
Something like this: 
https://github.com/geerlingguy/ansible-role-mysql/pull/228

**Comment by geerlingguy** [comment]
Fixed via above PR. Thanks!
