### ISSUE TITLE
Root password for hostname for local_action

### ISSUE THREAD

**Issue by solomongifford** [geerlingguy/ansible-role-mysql#23]
Related to #22, if local_action is used with a mysql install ansible_hostname is localhost and not the hostname of the machine and the root password is not set.

Suggestion would be to grab the results of:

command: 'mysql -NBe 'SELECT Host from mysql.user WHERE User = "root" order by (Host="localhost") ASC'

Note that this orders the localhost last so that ansible doesn't lock itself out.

**Comment by geerlingguy** [comment]
Nice. Silly me, trying to manipulate the result set with Python/Jinja2... when just adding the order statement to the MySQL statement would work perfectly.

This should be simple enough to do—thanks for reporting, and I'll try to get to this soon!

**Comment by geerlingguy** [comment]
Fixed in PR #28.
