### ISSUE TITLE
ansible-lint issues

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-role-mysql#231]
Ansible linting found 2 minors, adding a name is trivial. ANSIBLE0016 is debatable, add skip_ansible_lint tag to suppress. Fixing these allows molecule verification to continue with verification with tests.
 
```
[ANSIBLE0011] All tasks should be named
tasks/setup-Archlinux.yml:11
Task/Handler: command mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

[ANSIBLE0016] Tasks that run when changed should likely be handlers
tasks/setup-Archlinux.yml:11
Task/Handler: command mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
```

**Comment by geerlingguy** [comment]
Fixing the first one; for the second, that's awfully nitpicky—IMO ansible lint should not even warn on it because there are a ton of use cases where you would want to use `.changed` but not a handler.

**Comment by geerlingguy** [comment]
@bbaassssiiee - I don't use molecule, and would rather not add extra stuff to my roles that I don't need/use, at least not at this time. It would be better to turn off that warning/notice in ansible lint itself IMHO. (Similar issue exists when using linters in almost any language—there are some lints that are incredibly pedantic and should just be turned off unless you're incredibly strict about it :)
