### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by codeyy** [geerlingguy/ansible-role-mysql#239]
Since there is an option to enable error logging in MySQL, wouldn't it be interesting to also include some logrotate.d logic?

**Comment by geerlingguy** [comment]
@codeyy - I recommend people set up logrotate functionality using a separate role (I usually use the `nickhammond.logrotate` role myself, as it's very flexible).

Note that some people who use this role don't use/have logrotate available to them, so it wouldn't make sense to include any logrotate functionality in this role.
