### ISSUE TITLE
Initial replication

### ISSUE THREAD

**Issue by cmol** [geerlingguy/ansible-role-mysql#254]
Hi,

So I'm wondering about the replication usage of this role.

As far as I can understand, it seems to only be relevant for setting up replication of servers before they are loaded with data. However, if a sever needs to be added to to a cluster, an initial replication is missing.

My understanding of the replication workflow is:

- GRANT replication stuff on master
- [MISSING] LOCK TABLES on master
- [MISSING] dump database on master
- GET log pos and file and such on master
- [MISSING] UNLOCK TABLES on master
- [MISSING] Transfer dump to slave
- [MISSING] Load dump on slave
- CHANGE MASTER to master on slave
- Start replication on slave

Is this correctly understood? And are the [MISSING] parts indeed missing?

Thank you in advance
/ Claus

**Comment by amezioud** [comment]
Hi, 
I think you have a good inderstanding of this role. I guess we need to create the missing tasks by our own means. 😁

**Comment by cmol** [comment]
Hi,
I've totally forgotten about this and have since changed where I'm working so I have gotten away from the point where this makes sense to work on, at least right now. If you manage to find a solution though, let me know! :)
