### ISSUE TITLE
Local testing - Issue with Appamor and Ubuntu 16.04

### ISSUE THREAD

**Issue by laurentdavid** [geerlingguy/ansible-role-mysql#263]
While I was testing locally my playbooks on docker using the test shim (test/test.sh), running docker.

I was unable to install mysql on ubuntu 16.04. Still the travis test were successful on the same platform. 
The main issue was originally that the /etc/mysql/conf.d folder was not accessible. 
I digged more into it and followed a thread that took me to understand a bit more what was happening:

- Apparmor is preventing mysql from accesssing its files (configuration) (see issue.txt)
- Apparmor is trying to get a match of thoses files in a path that does not exist on the guest (I originally checked if it was not an issue with the overlay mount in docker).
- It is linked to the --privileged option of docker as if it is not launched with this option, the install goes well (also the service down the line cannot be launched).

Finally I got some explanation here: https://github.com/moby/moby/issues/7512#issuecomment-51845976
So this is due to the fact that the apparmor profile from the host is applied on the guest in privileged mode.

My workaround for now is to disable apparmor profile on the host 'just' before we start the test by doing a:

> sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
> sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

However this does not help much with starting the service later down the line when we start the service. 
Note the this only happens on 16.04.

This is in my opinion not a really important bug (as it seems that all other version 14 to 18 work for ubuntu), unless you really need 16.04. 
However I wanted to share this in case this is happening later in the future with another version/distro.

**Traces:** 

The original issue:
[issue.txt](https://github.com/geerlingguy/ansible-role-mysql/files/2098731/issue.txt)

A sample error in the /var/log/kern.org

Jun 13 15:04:04 efc19f34535c kernel: [ 4105.037609] audit: type=1400 audit(15289
02244.500:124): apparmor="DENIED" operation="open" info="Failed name lookup - di
sconnected path" error=-13 profile="/usr/sbin/mysqld" name="var/lib/docker/overl
ay2/625b053a7f720dbf3ee70b609e0a0b1c523071985244dc55f871e571a0aac1d2/diff/var/li
b/mysql" pid=30266 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=106 ou
id=106

**Comment by mvasilenko** [comment]
@laurentdavid  you could disable apparmor early during initialization, before starting mysql, with role like this:

https://github.com/Oefenweb/ansible-apparmor
