### ISSUE TITLE
Error connecting to MySQL socket in Ubuntu 18.04 Docker container

### ISSUE THREAD

**Issue by ergonlogic** [geerlingguy/ansible-role-mysql#265]
Using Packer's Ansible provisioner, I'm seeing the following error:

>     docker: TASK [geerlingguy.mysql : Disallow root login remotely] ************************
>     docker: failed: [localhost] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.416154", "end": "2018-06-20 19:16:28.300735", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "msg": "non-zero return code", "rc": 1, "start": "2018-06-20 19:16:27.884581", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"], "stdout": "", "stdout_lines": []}

**Comment by ergonlogic** [comment]
This looks like a bug with Ansible on Ubuntu Bionic: https://github.com/ansible/ansible/issues/37551#issuecomment-398915525. FWIW, this works:

    - name: Force start of mysql service.
      command: service mysql start

**Comment by hankpillow** [comment]
Same here. The role works fine when running the playbook on vagrant container but when provisioning a docker container (ubuntu:trusty) I saw the same error.
Adding these lines at the top of  **secure-installation.yml** fixed the problem:

```yml
- name: force start
  command: "service {{ mysql_daemon }} start"
 ```

Seems that the "restart apache" handler fired at the end of **configure.yml** has no effect. Not sure if "restart + sleep" could be the reason.

Using role version:
```
- src: geerlingguy.mysql
  version: 2.9.4
```

**Comment by hankpillow** [comment]
I also noticed that changing the task `# - name: Ensure MySQL is started and enabled on boot.` (configure.yml) 

from:
```
service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
```

to:
```
command: "service {{ mysql_daemon }} start"
```

worked.

**Comment by geerlingguy** [comment]
@hankpillow - If that fixes the issue, it means that Ansible's `service` module is broken, because behind the scenes that's exactly what it should be doing. Are you running the latest Ansible? (2.7.1 as of this writing).

**Comment by hankpillow** [comment]
You are right @geerlingguy , the role passed but it was not working properly when restarting the container. I've created this playbook https://gist.github.com/hankpillow/1071114b2943a7665f40aab3fbf46b0f to share how I'm trying to run the role.

Ansible Version: 2.7.1
python version 2.7.5

**Comment by ctorgalson** [comment]
@geerlingguy @hankpillow I see exactly the same behaviour on Ubuntu Xenial (in Docker only). Changing the `service` task to a `command` sorts the problem there too.
 
Looks @ergonlogic [is correct](https://github.com/geerlingguy/ansible-role-mysql/issues/265#issuecomment-398928799): it's the Ansible bug.
