### ISSUE TITLE
MariaDB >= 10.3 does not support innodb_large_prefix

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-mysql#272]
**Errors in log:**
unknown variable 'innodb_large_prefix=1'
unknown variable 'innodb_file_format=barracuda'

**Cause:**
Both `innodb_large_prefix` and `innodb_file_format` have been deprecated in mariadb 10.2 and have been removed in 10.3

**Workaround:**
Set playbook variable `mysql_supports_innodb_large_prefix` to false

**Comment by lucrus73** [comment]
I'm facing this issue, but I don't understand what `mysql_supports_innodb_large_prefix` variable does and how it works around the issue.

**Comment by racke** [comment]
Actually MariaDB 10.4.3 introduced that again for compatibility purposes (https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix).
