### ISSUE TITLE
check_mode broken

### ISSUE THREAD

**Issue by niavlysAO** [geerlingguy/ansible-role-mysql#274]
task "Copy my.cnf global MySQL configuration" fails in check_mode, because 'mysql_cli_version' is undefined.

it should be defined by  tasks/configure.yml (2-5)
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false

But this task is skipped in check_mode

**Comment by geerlingguy** [comment]
Looks good; if someone can provide a PR with that task enabled in check mode, I would be happy to merge it.

**Comment by andreykaipov** [comment]
Hey sorry! This is my fault because of the PR #273 for MySQL 8 compatibility.

PR #275 fixes this, but keep in mind it's only for subsequent runs. That is, check mode on a clean host will still fail as it did before. Don't really know how to get around that!
