### ISSUE TITLE
Running sql scripts

### ISSUE THREAD

**Issue by chuttipayan** [geerlingguy/ansible-role-mysql#287]
Hi 
is there a way i can run create table scripts  using this roles ?

I have created the DB i want to create the tables and insert few master data

thanks
Sunil Vikram

**Comment by geerlingguy** [comment]
@chuttipayan - The best way to load in data is to use the `mysql_db` module in your playbook, or to run commands directly—see this stack exchange answer for more info: https://stackoverflow.com/a/28193955

**Comment by chuttipayan** [comment]
Thanks
