### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: list index out of range

### ISSUE THREAD

**Issue by alec9** [geerlingguy/ansible-role-mysql#293]
Not sure whats happening, also I am pretty new to ansible galaxy github  and all that so pasting the code here which gives me an error when I attempt to install mysql on my controler machine. Also, I been looking for a playbook which can install mysql on my target machines which are centos7. I think this packages does that and im trying to figure it out how it works. 

Hopefully someone know to fix this:

`[osboxes@ansiblecontroler ~]$ ansible-galaxy install geerlingguy.mysql
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.9.4.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- extracting geerlingguy.mysql to /usr/share/ansible/roles/geerlingguy.mysql
ERROR! Unexpected Exception, this is probably a bug: list index out of range
to see the full traceback, use -vvv
[osboxes@ansiblecontroler ~]$ ansible-galaxy install geerlingguy.mysql -vvv
ansible-galaxy 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Opened /home/osboxes/.ansible_galaxy
Processing role geerlingguy.mysql
Opened /home/osboxes/.ansible_galaxy
- downloading role 'mysql', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=mysql
https://galaxy.ansible.com/api/v1/roles/435/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/435/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.9.4.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- extracting geerlingguy.mysql to /usr/share/ansible/roles/geerlingguy.mysql
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 332, in install
    self.path = self.paths[nextidx]
IndexError: list index out of range
[osboxes@ansiblecontroler ~]$`

**Comment by geerlingguy** [comment]
@alec9 - What version of Ansible / Ansible Galaxy are you running? It looks like maybe you're on a really old version and that's the issue? I am running 2.7.0. Check with `ansible --version`.

**Comment by geerlingguy** [comment]
Can you please update? 2.4 is a bit old (though it should still work), and maybe there was a fix in 2.4.x or 2.5, 2.6, or 2.7 that fixes this issue.

If not, this is an issue with Ansible Galaxy or the `ansible-galaxy` command line tool, it's not something I could help fix in this role. I would suggest opening an issue upstream: https://github.com/ansible/galaxy/issues
