### ISSUE TITLE
Installing MySQL 5.7 RedHat

### ISSUE THREAD

**Issue by ndantonio** [geerlingguy/ansible-role-mysql#294]
Hi @geerlingguy can you please help me how to install MySQL 5.7 on RedHat and not MariaDB. 

Thanks.

**Comment by geerlingguy** [comment]
You can do something like https://github.com/geerlingguy/ansible-role-mysql/issues/73#issuecomment-207068927

Basically you'd need to ensure the MySQL yum repository is added, and then change some variables for the mysql packages installed by this role. I think there may be some other issues in this role's issue queues with more examples.

However, I don't yet officially support installing MySQL (instead of MariaDB) on distributions which don't supply MySQL in their official repos, so I'll close out this issue for now.

**Comment by ndantonio** [comment]
> You can do something like [#73 (comment)](https://github.com/geerlingguy/ansible-role-mysql/issues/73#issuecomment-207068927)
> 
> Basically you'd need to ensure the MySQL yum repository is added, and then change some variables for the mysql packages installed by this role. I think there may be some other issues in this role's issue queues with more examples.
> 
> However, I don't yet officially support installing MySQL (instead of MariaDB) on distributions which don't supply MySQL in their official repos, so I'll close out this issue for now.

Copy that. Thanks Jeff!

**Comment by davidjoyce-okta** [comment]
@ndantonio @geerlingguy Hi, I was also dealing with this exact issue on CentOS, so the fix might be the same.

Update your system first with `sudo yum update`. In your task remove `mariadb-libs`:

```yaml
- name: Remove MariaDB libraries
  yum:
    name: mariadb-libs
    state: absent
  become: yes
```

From the existing documentation, run these tasks before calling the role: [Link to the section](https://github.com/geerlingguy/ansible-role-mysql#later-versions-of-mysql-on-centos-7).

However where it does `Override variables for MySQL (RedHat).` to `set_fact` change `mysql_packages` to `['mysql-community-server']` which should then install the correctly named yum package.

Hope this helps you out!

**Comment by ndantonio** [comment]
Hi @davidjoyce-okta should I put yum update and removing of MariaDB libs together with the pre-task before calling mysql role?

**Comment by davidjoyce-okta** [comment]
@ndantonio Yes perform those actions before the current 2 tasks in the `pre_tasks` section, that's what I've done on a fresh CentOS install just to be sure there's no conflict from any MariaDB libraries. The one consequence of removing `mariadb-libs` is it also removes the `postfix` mail server, which has it as a dependency.
