### ISSUE TITLE
Installation failed on AWS 2018.03 AMI RedHat-NA.yml

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [geerlingguy/ansible-role-mysql#295]
The following task fails because AWS doesn't have a version number:

```
- name: Include OS-specific variables (RedHat).
   include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
   when: ansible_os_family == "RedHat"
```

It looks for `RedHat-NA.yml`:

```
TASK [geerlingguy.mysql : Include OS-specific variables (RedHat).] *************
Thursday 01 November 2018  13:24:19 +1100 (0:00:00.038)       0:00:03.814 ***** 
fatal: [***]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'RedHat-NA.yml'\nSearched in:\n\t/home/adam/.ansible/roles/geerlingguy.mysql/vars/RedHat-NA.yml\n\t/home/adam/.ansible/roles/geerlingguy.mysql/RedHat-NA.yml\n\t/home/adam/.ansible/roles/geerlingguy.mysql/tasks/vars/RedHat-NA.yml\n\t/home/adam/.ansible/roles/geerlingguy.mysql/tasks/RedHat-NA.yml\n\t/home/adam/vars/RedHat-NA.yml\n\t/home/adam/RedHat-NA.yml on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

My `os_family` variable is correct:  `"ansible_os_family": "RedHat"` but `distribution_major_version` is: `"ansible_distribution_major_version": "NA"`

I don't know whether this should be filed as a bug or feature request (to support AWS AMIs).

**Comment by geerlingguy** [comment]
It would be a feature request, because I don't _explicitly_ support Amazon Linux in most of my roles, just "it works on RHEL and CentOS so it probably works on AZ" :)

However, I do have a new `amazonlinux2` docker image I could use for testing this role: https://hub.docker.com/r/geerlingguy/docker-amazonlinux2-ansible/ (alongside the other tests), which would be able to help make sure changes made to support CentOS/RHEL don't break AZ Linux.

**Comment by Dynatrace-Adam-Gardner** [comment]
OK, this is by no means a showstopper for me so let's reclassify as a feature request 👍

**Comment by andrewvttran** [comment]
@Dynatrace-Adam-Gardner, is there a way to bypass this step? I'm running into the same issue as you, while using an Amazon Linux as my Vagrant image.
