### ISSUE TITLE
Installation fails when trying to remove anonymous users

### ISSUE THREAD

**Issue by leo4ever** [geerlingguy/ansible-role-mysql#306]
I am running into an error when trying to install mysql-server on CentOS 7. 
Below is the output when using the option -vvvv
It seems like it may be something related to ssh configuration. Any pointers or suggestion would be very helpful
`
failed: [xx.xx.xx.xx] (item=mysql-db-server) => {
    "changed": false,
    "item": "mysql-db-server",
    "module_stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 558\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 10.106.24.80 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_PvB1ql/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
`

**Comment by JukkaUusisalo** [comment]
I got similar situation at CentOS 7.5. For me it is not related to ssh.
`failed: [xx.xx.xx.xx] (item=localhost) => {"changed": false, "item": "localhost", "module_stderr": "Shared connection to 172.24.10.36 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_LxKWRb/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 0}
`

**Comment by JukkaUusisalo** [comment]
For testing purpose, i removed "remove anonymous users" task and then  I run similar error with "Ensure MySQL users are present." task. Something with mysql_user ansible module?

**Comment by JukkaUusisalo** [comment]
update to Ansible 2.7 solves my problem.
