### ISSUE TITLE
touch /var/log/mariadb/mariadb.log gives an error

### ISSUE THREAD

**Issue by robjuffermans** [geerlingguy/ansible-role-mysql#314]
because /var/log/mariadb doesn't exists on a fresh install.

Tested on Centos 7.4

**Comment by keimond** [comment]
My task directly before the Create error log file task
`- name: Create logdir if it does not exist (if configured).`
`  file:`
`    path: "{{ mysql_log_error | dirname }}"`
`    state: directory`
`    owner: mysql`
`    group: mysql`
`    mode: 0755`
`    setype: mysqld_db_t`
`  when:`
`    - mysql_log == ""`
`    - mysql_log_error != ""`
`  tags: [skip_ansible_galaxy]  `
