### ISSUE TITLE
MariaDB 10.3.13 install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mvasilenko** [geerlingguy/ansible-role-mysql#316]
installing MariaDB 10.3 fails at Ubuntu 18.04

```
mysql_packages:
  - mariadb-client-10.3
  - mariadb-server-10.3

```

playbook fails with following error:

`
TASK [geerlingguy.mysql : Disallow root login remotely] ***************************************************************************************
failed: [beta-mariadb] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.006237", "end": "2019-03-11 17:46:51.958638", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "msg": "non-zero return code", "rc": 1, "start": "2019-03-11 17:46:51.952401", "stderr": "ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded", "stderr_lines": ["ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded"], "stdout": "", "stdout_lines": []}
`

workaround is described at #127 

```
---
- name: Enable plugin unix_socket
  command: mysql --defaults-file=/etc/mysql/debian.cnf -e "INSTALL PLUGIN unix_socket SONAME 'auth_socket'"
  register: mysql_result
  changed_when: mysql_result.rc == 0
  failed_when: mysql_result.rc != 0 and 'already installed' not in mysql_result.stderr
```

can we add it to MariaDB install tasks?

**Comment by zx1986** [comment]
It seems by default the database has no `root@127.0.0.1` ?

```
--------------
select user, host from mysql.user
--------------

+------------------+-----------+
| user             | host      |
+------------------+-----------+
| debian-sys-maint | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
+------------------+-----------+
````
