### ISSUE TITLE
MySQL takes time to restart, causing successive steps to sometimes fail

### ISSUE THREAD

**Issue by ergonlogic** [geerlingguy/ansible-role-mysql#33]
When provisioning a Vagrant VM on Ubuntu 14.04, we occasionally see something like the below. Unfortunately, it appears to be intermittent, and I've only been able to reproduce this behaviour once.

    [...]
    ==> valkyrie: NOTIFIED: [geerlingguy.mysql | restart mysql] ********************************* 
    ==> valkyrie: failed: [localhost] => {"failed": true}
    ==> valkyrie: msg:  * Stopping MySQL database server mysqld
    ==> valkyrie:    ...done.
    ==> valkyrie:  * Starting MySQL database server mysqld
    ==> valkyrie:    ...fail!
    ==> valkyrie: 
    ==> valkyrie: 
    ==> valkyrie: FATAL: all hosts have already failed -- aborting

Looking in the mysql error log shows the following:

    [...]
    # tail -30 /var/log/mysqld.log
    InnoDB: Unable to lock ./ibdata1, error: 11
    InnoDB: Check that you do not already have another mysqld process
    InnoDB: using the same InnoDB data or log files.
    InnoDB: Unable to lock ./ibdata1, error: 11
    InnoDB: Check that you do not already have another mysqld process
    InnoDB: using the same InnoDB data or log files.
    InnoDB: Unable to lock ./ibdata1, error: 11
    InnoDB: Check that you do not already have another mysqld process
    InnoDB: using the same InnoDB data or log files.
    150417 20:15:46  InnoDB: Unable to open the first data file
    InnoDB: Error in opening ./ibdata1
    150417 20:15:46  InnoDB: Operating system error number 11 in a file operation.
    InnoDB: Error number 11 means 'Resource temporarily unavailable'.
    InnoDB: Some operating system error numbers are described at
    InnoDB: http://dev.mysql.com/doc/refman/5.5/en/operating-system-error-codes.html
    150417 20:15:46 InnoDB: Could not open or create data files.
    150417 20:15:46 InnoDB: If you tried to add new data files, and it failed here,
    150417 20:15:46 InnoDB: you should now edit innodb_data_file_path in my.cnf back
    150417 20:15:46 InnoDB: to what it was, and remove the new ibdata files InnoDB created
    150417 20:15:46 InnoDB: in this failed attempt. InnoDB only wrote those files full of
    150417 20:15:46 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
    150417 20:15:46 InnoDB: remove old data files which contain your precious data!
    150417 20:15:46 [ERROR] Plugin 'InnoDB' init function returned error.
    150417 20:15:46 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
    150417 20:15:46 [ERROR] Unknown/unsupported storage engine: InnoDB
    150417 20:15:46 [ERROR] Aborting

    150417 20:15:46 [Note] /usr/sbin/mysqld: Shutdown complete

    150417 20:15:46 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended

Note that i believe this is the underlying issue behind https://github.com/GetValkyrie/valkyrie/issues/54, and it is in that context that I came across it.

**Comment by ergonlogic** [comment]
It looks like there is a `mysqld` process running, so perhaps a second one is started at some point...

**Comment by ergonlogic** [comment]
Could it be that [this](https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/setup-Debian.yml#L16) isn't aggressive enough. Maybe a straight-up `pkill mysqld`?

**Comment by geerlingguy** [comment]
Or a wait to make sure it's completely and totally shut down (it might take a while to shut down the first time). I am growing to dislike Debian/Ubuntu tremendously... between weird symlinked and changed-per-implementation paths and the terrible defaults and installation processes, it's an automation nightmare.

**Comment by ergonlogic** [comment]
So I guess that'd be accomplished with a 'sleep' parameter in the `restart mysql` handler?

**Comment by geerlingguy** [comment]
@ergonlogic - I'd still like to know what, in the environment, might be causing this issue. In my entire fleet of prod servers (mostly CentOS 6/7, but a good number (20+) Ubuntu 14.04 and 12.04), I've never had an issue where an instance of MySQL would get stuck :-/

I'm using the same role on [Drupal VM](http://www.drupalvm.com/), which uses the `geerlingguy/ubuntu1404` box (which doesn't have MySQL pre-installed), and nobody else seems to have run into the error.

**Comment by ergonlogic** [comment]
The intermittent nature of this behaviour makes it difficult to confirm. But, in the original bug report (https://github.com/GetValkyrie/valkyrie/issues/54#issue-65891116) the issue arises when we call a Drush command on a site right after restarting the mysql service, as part of flushing handlers.

Note that the `sleep` parameter to the [`service`](http://docs.ansible.com/service_module.html) module is described as:

    If the service is being restarted then sleep this many seconds between the stop and start command. This helps to workaround badly behaving init scripts that exit immediately after signaling a process to stop.

I've added a 5-second sleep in my fork of this role (https://github.com/geerlingguy/ansible-role-mysql/compare/master...GetValkyrie:master) that I've since included in Valkyrie. It seems somewhat heavy-handed, but I'm not in a position to be able to test this myself. Hopefully, one of the users who is seeing this more consistently can provide feedback.

**Comment by ergonlogic** [comment]
According to https://github.com/GetValkyrie/valkyrie/issues/54#issuecomment-94468470, it looks like adding a 'sleep' to the service restart handler worked.

**Comment by geerlingguy** [comment]
@ergonlogic - Ah, that makes sense then. I don't have anything run immediately after the restart, so the restart completes successfully by then.

I'll add a short sleep period to my role (5 seconds seems reasonable), since this could potentially affect others using the same init script, and it's not really a harmful change (just 5 more seconds every time the playbook is run... but an okay tradeoff).

**Comment by Prospus-ShantiGola** [comment]
> Could it be that [this](https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/setup-Debian.yml#L16) isn't aggressive enough. Maybe a straight-up `pkill mysqld`?

Thanks, it works ....after using this comand just start my mysql service straight away " sudo service mysql start" service start working again.
