### ISSUE TITLE
Does it support failover?

### ISSUE THREAD

**Issue by crazyacking** [geerlingguy/ansible-role-mysql#330]
Does it support failover?

**Comment by geerlingguy** [comment]
Technically yes, you can configure basic master/slave replication using this role. However any kind of actual failover implementation is not this role's responsibility, as it would add a huge level of complexity I'm not willing to support in a single Ansible role.

**Comment by crazyacking** [comment]
> Technically yes, you can configure basic master/slave replication using this role. However any kind of actual failover implementation is not this role's responsibility, as it would add a huge level of complexity I'm not willing to support in a single Ansible role.

Ok, I understand, thank you very much.
