### ISSUE TITLE
Unable to install mysql on debian 10 : No package matching 'mysql-server' is available

### ISSUE THREAD

**Issue by pulse-mind** [geerlingguy/ansible-role-mysql#336]
Hello,

First thank you for the job done on this role and others roles!

This is the error in the console:
```
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ***************************************************************************************************************
fatal: [172.31.2.226]: FAILED! => {"changed": false, "msg": "No package matching 'mysql-server' is available"}
```

**Comment by pulse-mind** [comment]
It looks like the packages should be : 
```mariadb-server
mariadb-client```

Source : https://computingforgeeks.com/how-to-install-mariadb-on-debian-10-buster/

**Comment by speedlight** [comment]
`mysql-server` is now `default-msql-server` the same for `mysql-client` maybe a new role for mariadb cloud be useful as some may need specifically mysql and not mariadb :)

**Comment by speedlight** [comment]
And, the variable `mysql_packages` help with this, like:
```sh
mysql_packages:
 - default-mysql-server
```
or 
```sh
mysql_packages:
 - mariadb-server
```

**Comment by pulse-mind** [comment]
Thank you @speedlight and what about ```__mysql_daemon: ``` ???

**Comment by geerlingguy** [comment]
Fixed via commit in #337. Thanks!

**Comment by hamzaabi** [comment]
changing the name=mysql-server-.....by **mariadb-server** fixed the issue

thank you very much

**Comment by dornier40** [comment]
> changing the name=mysql-server-.....by **mariadb-server** fixed the issue
> 
> thank you very much

Idem (for Debian 12)
