### ISSUE TITLE
Mysql module issue in Ansible after installing Python-MySQL dependencies

### ISSUE THREAD

**Issue by mdsajid786** [geerlingguy/ansible-role-mysql#349]
Hi All,

I'm trying to use MySQL module in ansible. 
I have installed the required modules in the Ansible controller. but still, it gives me below error. 

**Error while executing:**

 "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}

![image](https://user-images.githubusercontent.com/30176589/64347649-e6665b80-d011-11e9-9dbc-e72e1754a7fa.png)

**Playbook:**

![image](https://user-images.githubusercontent.com/30176589/64347743-131a7300-d012-11e9-9a33-dbbf5b8e8b0b.png)

**MySQL-python:**
 
![image](https://user-images.githubusercontent.com/30176589/64347991-2299bc00-d012-11e9-98d8-e07f956f6170.png)

**Python & Pip Verstion:**

![image](https://user-images.githubusercontent.com/30176589/64348095-37764f80-d012-11e9-832b-144a672442cb.png)

Request you to please help on this issue.

**Comment by fullofcaffeine** [comment]
I'm having the same issue...
