### ISSUE TITLE
Updating root password fails

### ISSUE THREAD

**Issue by ergonlogic** [geerlingguy/ansible-role-mysql#35]
I've just recently started seeing the following errors:
```
==> default: TASK: [ansible-role-mysql | Update MySQL root password for localhost root account.] *** 
==> default: failed: [localhost] => (item=mysql) => {"failed": true, "item": "mysql"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
==> default: failed: [localhost] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
==> default: failed: [localhost] => (item=::1) => {"failed": true, "item": "::1"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
==> default: failed: [localhost] => (item=localhost) => {"failed": true, "item": "localhost"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
```

**Comment by ergonlogic** [comment]
For context, this is running on Trusty64 in Vagrant on Ansible's `stable-1.9` branch. I've seen typos and other bugs on that branch before, so I'll test further on the latest release (1.8.4, iirc)

**Comment by ergonlogic** [comment]
This appears to also be an issue on Precise64 using Ansible's `release1.8.4` branch.

**Comment by ergonlogic** [comment]
I believe that I've (finally) found the root of this issue. While the `/root/.my.cnf` file was properly created, the default config file that the mysql_user module looks for is at `~/.my.cnf`. Somewhere between Vagrant's SSH, shell provisioning, and my calling of `ansible-playbook --sudo --connection=local ...`, `~` doesn't appear to have been expanding correctly into `/root/`.

In my fork, I've switched to using the (new in Ansible 2) `config_file` parameter for mysql_user: https://github.com/GetValkyrie/ansible-role-mysql/commit/fd00dc3ead1350823d0cfd3fc939cb35cad3fce5. Note that this is incompatible with Ansible 1.8.x and previous.

FWIW, I also [added a Vagrantfile](https://github.com/GetValkyrie/ansible-role-mysql/commit/41105a6fdda0e644a0506cd289a320876a63f374), and switched to [installing Ansible from sources](https://github.com/GetValkyrie/ansible-role-mysql/commit/4028e6ebd89976d42b77fdff9a767828b5f92c26). Cherry-picking these into a feature branch is an easy way to re-produce this issue, if you'd like to work on a backward-compatible solution.

**Comment by geerlingguy** [comment]
Looks like a good option; I'm going to open a new issue to track this, and once Ansible 2.0 is released as the stable branch, I'll probably add this in and up the requirement for this role. For now, I want to keep it compatible with the latest stable release.
