### ISSUE TITLE
CentOS 8/RedHat 8 support

### ISSUE THREAD

**Issue by mhitza** [geerlingguy/ansible-role-mysql#367]
While the PR is open I've created a few release on my work fork https://github.com/mhitza/ansible-role-mysql/releases

To use the release I've packaged you can switch out in your Ansible Galaxy file
```
- src: https://github.com/mhitza/ansible-role-mysql/archive/1.2.tar.gz
  name: geerlingguy.mysql
```

I prefer to give it a more obvious name myself, like `ansible-role-mysql-fork-redhat-8` just so it stands out as a workaround.

**Comment by pulse-mind** [comment]
Thank you, please accepte this PR. It is working fine. 
And please publish on galaxy

**Comment by mhitza** [comment]
PR just got merged and it's going to be in the followup release > 2.9.6

**Comment by geerlingguy** [comment]
Fixed, thanks!
