### ISSUE TITLE
Is it possible to avoid storing passwords in my.cnf?

### ISSUE THREAD

**Issue by m8ram** [geerlingguy/ansible-role-mysql#370]
The `mysql_db` and `mysql_user` support `login_user` and `login_password`. Is it possible to update this role to use those instead of using a `my.cnf` file?

**Comment by fishhead108** [comment]
Up

**Comment by tisba** [comment]
We'd also be interested if this is possible.

**Comment by m8ram** [comment]
@geerlingguy : can you re-open this please?
