### ISSUE TITLE
Debian 9 MariaDB service fails to start

### ISSUE THREAD

**Issue by gevalo1** [geerlingguy/ansible-role-mysql#377]
I'm using this role to install MariaDB (10.4) on Debian 9, however out of the box it seems to fail on the following step: `geerlingguy.mysql : Ensure MySQL is started and enabled on boot.`
https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/configure.yml#L85

The error I'm given is:
```
Unable to start service mysql: Job for mariadb.service failed because the control process exited with error code.
```

I found that running `mysql_install_db` allows me to start the service successfully.

Am I forgetting some configuration somewhere or is this command missing from the Debian installation playbook?

**Comment by srgvg** [comment]
I'm having this same issue, when changing mysql's `datadir` to another location. As basedir is not being set, it seems to default to the same `datadir`, and at this subsequent restart, it can't find it's originally at install created system databases.

**Comment by Zauberstuhl** [comment]
mh this is still an issue :( please reopen
