### ISSUE TITLE
Please reopen "Default insecure passwords seems bad #223"

### ISSUE THREAD

**Issue by colans** [geerlingguy/ansible-role-mysql#381]
Just in case there are no more notifications on that issue, please reopen #223 as I'm not able to myself.  Thanks!

**Comment by colans** [comment]
This still hasn't been acted upon.

**Comment by colans** [comment]
This still hasn't been acted upon.

**Comment by colans** [comment]
This still hasn't been acted upon.

**Comment by geerlingguy** [comment]
Reopened the other issue.
