### ISSUE TITLE
handler do not execute after task

### ISSUE THREAD

**Issue by mnothic** [geerlingguy/ansible-role-mysql#39]
sorry but the restart of mysql in the handler never does during vagrant provision
 you know why?

**Comment by geerlingguy** [comment]
It should be happening, unless you have something else failing out before notify handlers are called. Besides trying to switch to Ansible devel (latest) or 1.9.0.1 (which resolves one weird bug that sometimes causes MySQL's current state to not be read correctly), this seems like it would be something solved upstream.
