### ISSUE TITLE
python interperter not recognized on Ubuntu 20.04

### ISSUE THREAD

**Issue by KaiShunOleander** [geerlingguy/ansible-role-mysql#394]
setup-Debian uses anisble_python_interperter to determine the python version, which however isnt set on the Ubuntu platform. Using discovered_interperter_python instead works fine.

Playbook results in the error:
fatal: [os-asset]: FAILED! => {"changed": false, "msg": "No package matching 'python-mysqldb' is available"}

$ ansible os-asset -m setup | grep python
        "ansible_python": {
            "executable": "/usr/bin/python3", 
            "type": "cpython", 
        "ansible_python_version": "3.8.2", 
        "ansible_selinux_python_present": false, 
        "discovered_interpreter_python": "/usr/bin/python3", 

Ansible version used: 2.9.9

**Comment by KaiShunOleander** [comment]
ansible-inventory shows this:
    hosts:
        os-asset:
          WelcomeMessage: Welcome, Spirit!!!
          admin_group: opensim
          admin_user: gridadmin
          ansible_python_interperter: /usr/bin/python3

**Comment by KaiShunOleander** [comment]
setting ansible_python_intepreter in ansible.cnf doesnt work;
[all:vars]
ansible_python_interperter=/usr/bin/python3

setting the variable in pre_tasks: section does work:
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined
    
    roles:
      - geerlingguy.mysql

**Comment by MVKozlov** [comment]
ansible_python.version.major == 3 also works

**Comment by rivimey** [comment]
I too came across his problem, and have solved it with this patch to setup-Debian:

diff --git a/setup-Debian.yml b/setup-Debian.yml
index 325f25c..5a61940 100644
--- a/setup-Debian.yml
+++ b/setup-Debian.yml
@@ -7,9 +7,21 @@
   apt: update_cache=yes
   when: not mysql_installed.stat.exists

+- name: Determine required MySQL Python libraries (Ubuntu Focal Fossa ++)
+  set_fact:
+    mysql_python_package_debian: "python3-pymysql"
+  when:
+    - mysql_python_package_debian is not defined
+    - ansible_distribution == "Ubuntu"
+    - ansible_distribution_major_version|int > 19
+
 - name: Determine required MySQL Python libraries.
   set_fact:
-    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"
+    mysql_python_package_debian: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"
+  when:
+    - mysql_python_package_debian is not defined
+    - ansible_distribution != "Ubuntu"
+    - ansible_distribution_major_version|int < 20

 - name: Ensure MySQL Python libraries are installed.
   apt:

**Comment by basictheprogram** [comment]
With commit b33c4b76edcee3e29934d3e4acbc22e0f2189d3f I cannot duplicate this problem. Did the code base change? The Ubuntu 20.04 docker image change? Did the someone fix the issue with Ubuntu 20.04?
```
$ ansible --version
ansible 2.9.10.post0
  config file = None
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.8.3 (default, Jul  7 2020, 13:01:48) [Clang 11.0.0 (clang-1100.0.33.17)]
```
```
$ molecule --version
molecule 3.0.4
```
All tests pass
  * [MOLECULE_DISTRO=ubuntu2004 molecule test](https://gist.github.com/basictheprogram/0addddc661a1d2ef45310b2b3c50d9cf)
  * [MOLECULE_DISTRO=ubuntu2004 molecule coverge](https://gist.github.com/basictheprogram/71cb692efed2c172a355cc950e58f783)

```
$ molecule login
$ dpkg -l | grep mysql

ii  libmysqlclient21:amd64        8.0.20-0ubuntu0.20.04.1     amd64        MySQL database client library
ii  mysql-client-8.0              8.0.20-0ubuntu0.20.04.1     amd64        MySQL database client binaries
ii  mysql-client-core-8.0         8.0.20-0ubuntu0.20.04.1     amd64        MySQL database core client binaries
ii  mysql-common                  5.8+1.0.5ubuntu2            all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                  8.0.20-0ubuntu0.20.04.1     all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-8.0              8.0.20-0ubuntu0.20.04.1     amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-8.0         8.0.20-0ubuntu0.20.04.1     amd64        MySQL database server binaries
ii  python3-mysqldb               1.4.4-2build1               amd64        Python interface to MySQL
```

**Comment by MVKozlov** [comment]
according [ansible doc](https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html)
"To explicitly configure a Python 3 interpreter, set the `ansible_python_interpreter`"
so use it for version check seems discouraged because it may be not set at all

**Comment by rivimey** [comment]
@basictheprogram I have been using geerlingguy's ubuntu2004 vbox VM, not docker.
@MVKozlov the patch I checks the interpreter variable because if it is set it needs to be honoured.

**Comment by basictheprogram** [comment]
@rivimey I am also using geerlingguy's ubuntu2004 docker image. 

Are you building a vagrant box and testing that inside virtualbox? 

Let me know if that's the case and I'll test things in that environment.

**Comment by KaiShunOleander** [comment]
I used Oracle VMBox , no Vragant used.

**Comment by rivimey** [comment]
@basictheprogram 

I use vagrant + DrupalVM, with config.yml specifying the vagrant box geerlingguy/ubuntu2004.

My Vagrant is using Virtualbox, but I'm pretty sure this issue is related to a configuration change by the ubuntu distribution, not the vm runtime.

Have a go running latest DrupalVM against a VM of ubuntu 20.04

**Comment by MVKozlov** [comment]
@rivimey afaik `ansible_python.version.major` already honor `ansible_python_interpreter` and your code will install v2 libraries if `ansible_python_interpreter` not defined but python3 installed and found by ansible automatic detection

**Comment by john-999** [comment]
Could this be linked to https://github.com/geerlingguy/ansible-role-mysql/issues/410 ?

**Comment by Preen** [comment]
Having this issue as well. The pre_task solution doesnt work for me either.

```
- name: Set up Mariadb
  hosts: db
  become: yes
  gather_facts: yes
  vars_files:
    - vars/mariadb.yml
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
        when: ansible_python_interpreter is not defined
  roles:
    - { role: geerlingguy.mysql }

**Comment by gnorbsl** [comment]
Having the same issue, neither adding the python interpreter to my hosts file nor adding it as a pre task is working.

**Comment by TipiT** [comment]
> @basictheprogram
> 
> I use vagrant + DrupalVM, with config.yml specifying the vagrant box geerlingguy/ubuntu2004.
> 
> My Vagrant is using Virtualbox, but I'm pretty sure this issue is related to a configuration change by the ubuntu distribution, not the vm runtime.
> 
> Have a go running latest DrupalVM against a VM of ubuntu 20.04

Are you sure you don't have something like this in you config.yml

`mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb`

and changing to 'python3-mysqldb' fixes the issue?
