### ISSUE TITLE
Setting datadir fails

### ISSUE THREAD

**Issue by pvanhemmen** [geerlingguy/ansible-role-mysql#399]
OS: Ubuntu Server 18.04 / 20.04
Ansible: 2.9.6

When setting `mysql_datadir` to something different, e.g. `/data/mysql` at initial setup, the mysql server fails to start. It seems mysql still initializes all files in `/var/lib/mysql` and then tries to start with the appropriate settings in `my.cnf` in place but an empty `/data/mysql` directory.

**Comment by KaiShunOleander** [comment]
I Get the same issue. error log files contains:

[System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060

I did add the new path to appormor, also added it as an alias but that didnt help. Still refuses the start Ansible file looks like this:

 hosts: os-asset
  become: yes
  gather_facts: yes
  vars:
    mysql_datadir: /vardb/mysql
    mysql_config_include_files:
      - src: authentication.cnf
    mysql_databases:
      - name: "{{ db_name }}"
        collation: utf8_general_ci
        encoding: utf8
        state: present

    mysql_users:
      - name: "{{ db_user }}"
        host: localhost
        password: "{{ db_password }}"
        priv: "*.*:ALL"

  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined

  roles:
    - geerlingguy.mysql
    - percona

**Comment by KaiShunOleander** [comment]
strabge the error log files says port 33060

**Comment by KaiShunOleander** [comment]
searched the web for hours but there doesnt seem a solution that works, so i made a symbolic link  from /var/lib/mysql to the new location

**Comment by pvanhemmen** [comment]
yes that's what I did, too. Setting the datadir in the postgre role https://github.com/geerlingguy/ansible-role-postgresql does work without a problem btw.

**Comment by daltonporter** [comment]
same issue here. any chance it can be fixed?

**Comment by garbast** [comment]
I have the same problem. My mysql_datadir is configured to /home/mysql and i did manually the following
```
cp -R /var/lib/mysql/* /home/mysql
chown -R mysql /home/mysql/mysql
chown -R mysql /home/mysql/performance_schema
chown -R mysql /home/mysql/ib_buffer_pool
/etc/init.d/mysql start
```
So it should not be to difficulty to change the configure.yml after line 53 to copy the files and modify the access rights.

**Comment by garbast** [comment]
Any idea when or if this will get fixed?

**Comment by misilot** [comment]
What I ran into for Ubuntu was having to add 

```alias /var/lib/mysql/ -> /new/data/dir/,```

to     /etc/apparmor.d/tunables/alias

**Comment by agnesdober-db** [comment]
Although I do not use this role, the comments on this issue helped me out, so I wanted to post what worked for me (also Ubuntu 20):

# With datadir specified to mounted volume
- name: Install mysqld.cnf
  ansible.builtin.template:
    src: 'mysqld.cnf.j2'
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: '0644'
    owner: root
    group: root

- name: Add alias to AppArmor
  ansible.builtin.lineinfile:
    path: /etc/apparmor.d/tunables/alias
    line: "alias /var/lib/mysql/ -> /mnt/mysql,"
    state: present
    insertafter: EOF
  notify:
    - Restart apparmor

- name: Synchronization of default with new on mount
  ansible.posix.synchronize:
    src: "/var/lib/mysql/."
    dest: /mnt/mysql
    perms: yes
  delegate_to: "{{ remote }}"
  notify:
    - Restart mysql

(Basically, don't forget to restart apparmor after the alias)
