### ISSUE TITLE
Get list of hosts for the root user fails with access denied error

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/ansible-role-mysql#40]
Just got the following while trying provision a Digital Ocean droplet:

```
TASK: [ansible-role-mysql | Get list of hosts for the root user.] *************
failed: [some.ip.address] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"root\" ORDER BY (Host=\"localhost\") ASC"], "delta": "0:00:00.007364", "end": "2015-06-04 12:54:13.586212", "rc": 1, "start": "2015-06-04 12:54:13.578848", "stdout_lines": [], "warnings": []}
stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

I've used this role with success in the past, having not used it in a while I pulled an updated version and re-ran today (first time I've seen this error).

**Comment by boukeversteegh** [comment]
I have the same error. I have an existing mysql database, and wanted to run this role to ensure that the correct tables and users exist, but it fails on this task

**Comment by scil** [comment]
i have the same error
```
TASK: [geerlingguy.mysql | Get list of hosts for the anonymous user.] *********

failed: [localhost] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host
FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.024041", "end": "2015-06-
15 12:23:12.498852", "rc": 1, "start": "2015-06-15 12:23:12.474811", "stdout_lin
es": [], "warnings": []}
stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using pas
sword: NO)

```

**Comment by geerlingguy** [comment]
I'm now sometimes getting:

```
TASK: [geerlingguy.mysql | Get list of hosts for the root user.] ************** 
failed: [drupaldev] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"root\" ORDER BY (Host=\"localhost\") ASC"], "delta": "0:00:00.004044", "end": "2015-06-19 19:29:25.622041", "rc": 1, "start": "2015-06-19 19:29:25.617997", "stdout_lines": [], "warnings": []}
stderr: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

If running the playbook when MySQL was never started correctly (e.g. first provisioning/boot didn't actually start MySQL for some reason).

It seems the following task (which reports `ok` on my environment) is not _actually_ `ok`; or else maybe MySQL is not listening on a socket/port correctly...

```
- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
```

**Comment by geerlingguy** [comment]
I think this *could* be a bug with Ubuntu 14.04 (and possibly 12.04) service handling with Ansible's `service` module in 1.9.1. Going to downgrade to 1.9.0.1 and see if it's cleared up...

**Comment by geerlingguy** [comment]
This *particular* bug just seems to indicate that MySQL needs a restart (at least in the few cases I've seen it happening)—most often because MySQL is listening only on at TCP port, and needs to be restarted to listen on a socket.

**Comment by geerlingguy** [comment]
And note that simply switching to Ansible 1.9.0.1 has fixed all the issues for me. 1.9.2 should also work, but it's still only in rc1 status (See: https://groups.google.com/forum/#!topic/ansible-devel/jfm6pZSLUYY).

So as a workaround, please do the following (if you installed Ansible with pip):

```
sudo pip uninstall ansible
sudo pip install ansible==1.9.0.1
```

Hopefully that solves the problem for others until Ansible 1.9.2+ is released!

**Comment by mglaman** [comment]
Just chiming in for others who arrive here: having some issues on ubuntu 14.04 and packer.io builds, giving downgrade a whirl as @geerlingguy mentioned.

**Comment by ryall** [comment]
This issue isn't resolved for me on 1.9.2, however I don't get the socket error but rather the access denied error as the original poster mentioned.

I have checked and the password is working and correct. One thing I changed was the root password.

    failed: [elm.keksia.io] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"root\" ORDER BY (Host=\"localhost\") ASC"], "delta": "0:00:00.018556", "end": "2015-08-19 22:05:27.978659", "rc": 1, "start": "2015-08-19 22:05:27.960103", "stdout_lines": [], "warnings": []}
    stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by rvanbaalen** [comment]
Im experiencing this issue on Ansible 1.9.3

**Comment by geerlingguy** [comment]
@rvanbaalen - Can you try setting `mysql_root_password_update` to `yes` in your variables, and see if that makes this work?

**Comment by danbohea** [comment]
Still experiencing this bug with Ansible 2.0.1.0.

Setting `mysql_root_password_update` to `yes` as suggested above seems to work.

**Comment by perchten** [comment]
I'm also getting this. 
```
TASK: [geerlingguy.mysql | Get list of hosts for the anonymous user.] *********
failed: [54.194.51.168] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.004040", "end": "2016-03-24 17:47:36.733753", "rc": 1, "start": "2016-03-24 17:47:36.729713", "stdout_lines": [], "warnings": []}
stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

I have tried the following configurations and all 3 generate this error:

Basic config:
```
overwrite_global_mycnf: yes
mysql_databases:
  - name: <mydbname>
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: <myusername>
    host: "localhost"
    password: <myuserpassword>
    priv: "<mydbname>.*:ALL"
mysql_enabled_on_startup: yes
```

Adding root `mysql_root_password`:
```
mysql_root_password: <myrootpassword>
```

And then adding `mysql_root_password_update: yes`
```
mysql_root_password: <myrootpassword>
mysql_root_password_update: yes
```


I'm using the most up-to-date ansible as provided by brew.
```
$ ansible --version
ansible 1.9.3
```

In between attempts I killed mysql by running:
```
#! /bin/bash

sudo service mysql stop
sudo apt-get purge -y mysql-server mysql-client mysql-common mysql-server-core-5.5 mysql-client-core-5.5
sudo rm -rf /etc/mysql /var/lib/mysql
sudo apt-get -y autoremove
sudo apt-get autoclean
sudo rm ~/.my.cnf
sudo rm -r /etc/mysql/
```

I'll keep trying to find a solution, but if you have a suggestion that would be great. I'll post if I work it out.

**Comment by danbohea** [comment]
@perchten Maybe try installing Ansible via pip rather than brew? That way you can go higher than v1.9.3 (v2 is now latest stable).

**Comment by perchten** [comment]
will try that - have had pain-in-the-ass issues with pip before. But that's unrelated.

Just wanted to say, a restart of mysql server just before that task had no impact. Just fyi.

**Comment by perchten** [comment]
Upgraded to 2.0.1.0. No luck. Still the same error as I posted above.

What sticks out for me - maybe wrongly - is that the error is for root access without password (`Access denied for user 'root'@'localhost' (using password: NO)`). Surely, given that this follows the tasks which set the root password, this call should be using the password, no?

I suggest reopening this issue. The offered solution is just a workaround, and now there's evidence it doesn't work in all cases.

**Comment by niccolox** [comment]
I am getting the same error on Travis Ubuntu Trusty vm and not on Vagrant Trusty

so, nice and obscure for sure

this is my play, which does not work

---

> - hosts: localhost
>   remote_user: root
>   become_user: root
>   become: yes
>   become_method: sudo
>   vars:
>     # Use default log file size so Travis CI VM allows MySQL restart.
>     - mysql_innodb_log_file_size: "5M"
>     - mysql_root_username: root
>     - mysql_root_password: root
>     - mysql_root_password_update: yes
>   roles:
>     - role: geerlingguy.mysql
>       become_user: root
>       become: yes
>       become_method: sudo
>     - role: getvalkyrie.drush
>     - role: ansible-role-aegir
>

**Comment by Marian0** [comment]
Same error here using Ubuntu 16.10 x64

**Comment by panickervinod** [comment]
Same error using Ubuntu 16.04, able to login interactively , using mysql -u root -p 
but fail in the playbook and also if I try mysql -Nbe ...
