### ISSUE TITLE
Add instructions for use with Percona

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-mysql#41]
I'm thinking it may be up to the consumer of the role to get the Percona repo configured, but it seems like it should be relatively easy to support Percona like I do for MySQL and MariaDB, as is shown in #19.

More info for Percona setup:
- [Installing Percona Server 5.6 from Binaries](https://www.percona.com/doc/percona-server/5.6/installation.html)
- [Percona apt Repository](https://www.percona.com/doc/percona-server/5.6/installation/apt_repo.html)
- [Percona yum Repository](https://www.percona.com/doc/percona-server/5.6/installation/yum_repo.html)

**Comment by bvansomeren** [comment]
Hi Jeff,

Thanks and sorry for not getting back to you sooner. I got stuck initially, but now have a working set of vars / steps for this role and it works great :)

First of all, ensure the Percona repo is added:

```
- yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present
```

And you need these vars (wherever you want to define them)

```
mysql_packages:
  - Percona-Server-client-56
  - Percona-Server-server-56
  - Percona-Server-shared-56
  - MySQL-python
  - perl-DBD-MySQL
mysql_daemon: mysql
mysql_log_error: /var/log/mysql.log
mysql_syslog_tag: mysql
mysql_pid_file: /var/run/mysql/mysql.pid
```

This was tested on CentOS 7

**Comment by paulmaunders** [comment]
Thanks @bvansomeren - this worked for me too, also tested on Centos 7.

**Comment by geerlingguy** [comment]
Awesome. We'll need to get this into the README. Hopefully I'll have some time to do that soon.

**Comment by bvansomeren** [comment]
Minor update.

The same works for CentOS 6, with the exception that you must redefine mysql_pid_file to:

```
mysql_pid_file: /var/lib/mysql/mysql.pid
```

If you use anything else or leave it to the role default Percona will not be able to start.
Would you like me to do a PR with the changes to the README file for you, I can add it to my TODO list for tomorrow :)

**Comment by geerlingguy** [comment]
@bvansomeren Please send me a PR, and I'll merge it. Traveling all month, pretty much, so simple PRs have a much greater chance of getting merged right now than me doing it myself :)

**Comment by memiah-steve** [comment]
As of geerlingguy.ansible-role-mysql 2.2.0 this approach doesn't appear to work.

Some of the variables are defined in `vars/RedHat-7.yml` rather than `defaults/main.yml`, therefore can't easily be overridden, and you get the following error.

```
TASK [geerlingguy.mysql : Create error log file (if configured).] **************
fatal: [database]: FAILED! => {"changed": true, "cmd": "touch /var/log/mariadb/mariadb.log", "delta": "0:00:00.006012", "end": "2016-08-18 12:07:14.222524", "failed": true, "rc": 1, "start": "2016-08-18 12:07:14.216512", "stderr": "touch: cannot touch ‘/var/log/mariadb/mariadb.log’: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": ["Consider using file module with state=touch rather than running touch"]}
```

Unfortunately, don't think I'll have the time at the moment to create a PR.
