### ISSUE TITLE
Provide MariaDB 10.4 out-of-the-box via config.yml

### ISSUE THREAD

**Issue by Melsi** [geerlingguy/ansible-role-mysql#414]
As proposed in geerlingguy/drupal-vm#2027 by [dercheffe](https://github.com/dercheffe):

> Per default Ubuntu 18.04 provides only MariaDB 10.1 out of the box.
>
> There should be a configuration option in config.yml to get MariaDB 10.4 also for Ubuntu 18.4
>
> https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=one&version=10.4
>
> Perhaps its even possible to add additional Ubuntu (or other Linux distro) PPA's to get newer packages in general.

Haven't found any other issue regarding this topic yet.

**Comment by axroth** [comment]
Hi @geerlingguy , do you have an idea on how to do this? This blocks drupal 9 usage in drupalvm(docker) right now. Cheers

**Comment by fliespl** [comment]
I was able to get mariadb 10.5 working on ubuntu 20.04 by using such tasks before using this role.

`    - name: Add apt key for MariaDB
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F1656F24C74CD1D8
    - name: Add apt repo for MariaDB
      apt_repository:
        repo: deb [arch=amd64,arm64,ppc64el] https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.5/ubuntu {{ ansible_distribution_release }} main
        state: present
        filename: mariadb
        update_cache: true
    - name: Create a symbolic link
      file:
        src: /etc/init.d/mariadb
        dest: /etc/init.d/mysql
        owner: root
        group: root
        force: true
        state: link`

Symbolic link was needed cause mariadb changed it's init.d script to be named "mariadb".
