### ISSUE TITLE
Unable to find out how to install Mysql 5.7 on Ubuntu 20

### ISSUE THREAD

**Issue by zagrad** [geerlingguy/ansible-role-mysql#428]
Since our production servers still run Mysql 5.7, I would like to install Mysql 5.7 instead of the default 8.0 on our Ubuntu-20 development servers.
I have been reading your documentation extensively and I have also Googled a lot, but I just can't find out how to do that.

I actually would expect a simple "mysql-version" variable, but that does not seem to be the case.

Can you help please?

**Comment by rubo77** [comment]
Maybe this works: https://gitlab.com/-/snippets/2065593
