### ISSUE TITLE
Getslave operation always fails while configuring the replication slave

### ISSUE THREAD

**Issue by blajos** [geerlingguy/ansible-role-mysql#435]
Mysql_replication_user is not created on the replication slave, so this task fails reliably:
https://github.com/geerlingguy/ansible-role-mysql/blob/3a164a5d0867e7b5e85e067fb260d21b1132213e/tasks/replication.yml#L15

I think the solution is to remove login_user and login_password from the task.

**Comment by dorianm** [comment]
Same problem here. I try with your fix (#436) and it works ! Thank you !
