### ISSUE TITLE
Module fails to interact with database due to missing python 2 module

### ISSUE THREAD

**Issue by thorian93** [geerlingguy/ansible-role-mysql#438]
Python interpreter: Python 2

Affected OS:
- Debian 9
- Debian 10
- Ubuntu 18.04

I took the role as is and ran it against the server which got me the following message:

    TASK [geerlingguy.mysql : Remove MySQL test database.] **************************************************************
    fatal: [server]: FAILED! => {"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}

As far as I understand the role should make sure the proper Python modules are installed, right?
I build my own role some time ago and took care of that but I can not figure out, why this does not work here.
Any hint to what I am doing wrong?

**Comment by thorian93** [comment]
To elaborate: This does not happen on Ubuntu 20.04.

**Comment by 1977er** [comment]
As a quick&dirty workaround you can do something like `mysql_packages: ['mariadb-server', 'python-pymysql', 'python3-pymysql']` in your variable section.

**Comment by esprit-libre** [comment]
You can also use [this tip](https://github.com/geerlingguy/ansible-role-mysql/issues/410#issuecomment-696748983) in `ansible.cfg`:
```
 interpreter_python = /usr/bin/python3
```

**Comment by geerlingguy** [comment]
Hmm... also see https://github.com/geerlingguy/ansible-role-mysql/issues/445

On RHEL 8, `python3-PyMySQL` is in the dependencies installed.

On Debian 10, I only have `default-mysql-server`. Maybe installing `python3-pymysql` would fix this?

**Comment by thorian93** [comment]
I just tested against Ubuntu 18.04 and the issue is the same as in Debian 10.

**Comment by thorian93** [comment]
I might be totally of course here, but would it be an idea to define those prerequisites in the OS-specific variable files once they become necessary? I do that in some of my roles and it works arguably good. Also you already have some of those files in use. That way you can go with the defaults as long as they work but you are able to set specific packages for specific distributions.

**Comment by thorian93** [comment]
I just realized that this issue depends on the python interpreter. Forcing Ansible to use Python 3 solves the issue. Apparently the problem is Python 2 and the related packages. Is this even something you want to address @geerlingguy or do you see that as out of scope for your role?

**Comment by geerlingguy** [comment]
@thorian93 - Since this seems to be something that could be very environment/OS-dependent, I'd rather not try to solve the python package problem in this role (unless it's something in this role that is causing the issue).

**Comment by baradhili** [comment]
No forcing ansible to use python3 doesn't fix this.. it is showing up in community.mysql as well.. for some reason ansible can't see pymysql - even if it is asked to install it itself.

**Comment by thorian93** [comment]
Interesting, for me it worked. I will keep an eye on it and update if I find anything worth mentioning.

**Comment by daraul** [comment]
Setting my python interpreter doesn't seem to fix this issue for me. If I do "molecule converge" twice, the 2nd run will work. The 1st will fail. I'm a little confused about why this happens, though.

**Comment by daraul** [comment]
Setting the ~mysql_packages~ variable as @1977er recommended *seems* to work, but now I get another error at "geerlingguy.mysql : Remove MySQL test database.". This is on ubuntu:18.04

**Comment by daraul** [comment]
I figured out a solution that works for me. I had to install python3.6 *manually* (or, in prepare.yml). Then I define that as my interpreter: `ansible_python_interpreter: /usr/bin/python3.6`. I haven't tested on later versions of python, but I can't imagine they wouldn't work.
