### ISSUE TITLE
Setting mysql_datadir on Ubuntu to a directory other than /var/lib/mysql, mysql fails to start

### ISSUE THREAD

**Issue by misilot** [geerlingguy/ansible-role-mysql#444]
When setting ```mysql_datadir``` on Ubuntu to a directory other than ```/var/lib/mysql``` causes mysql to fail to start.

This appears to be due to apparmor. 

Adding 
```alias /var/lib/mysql/ -> {{ mysql_datadir }}/,``` to /etc/apparmor.d/tunables/alias seems to resolve this. Could the role be updated to include this change?

Thanks!

**Comment by 1977er** [comment]
Same on Debian buster. `mysql_datadir` is set in `my.cnf`, but initial databases are created in `/var/lib/mysql` nonetheless.

**Comment by aded** [comment]
Same here. The solution proposed by @misilot works (alias added before playing this role, and then apparmor restarted).
See also https://linuxhint.com/change_mysql_data_directory_ubuntu/

**Comment by aded-cmcc** [comment]
> Same here. The solution proposed by @misilot works (alias added before playing this role, and then apparmor restarted).
> See also https://linuxhint.com/change_mysql_data_directory_ubuntu/

Actually there is another problem, apart from apparmor.

```
$ sudo grep -rni datadir /etc/mysql/*
/etc/mysql/mariadb.conf.d/50-server.cnf:21:datadir                 = /var/lib/mysql
/etc/mysql/my.cnf:13:datadir = /data/mysql
```

Related issue: #360
