### ISSUE TITLE
MySQL 5.5 using remi repo failed start

### ISSUE THREAD

**Issue by kakawait** [geerlingguy/ansible-role-mysql#47]
by using `epel` or `base` repo no problem but when enabling `remi` repo I have the following error:

```
TASK: [geerlingguy.mysql | Ensure MySQL is started and enabled on boot.] ******
failed: [localhost] => {"failed": true}
[Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
[Note] /usr/libexec/mysqld (mysqld 5.5.45) starting as process 9010 ...
[Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
[Note] /usr/libexec/mysqld (mysqld 5.5.45) starting as process 9017 ...
```

**Comment by geerlingguy** [comment]
I haven't had this issue on CentOS 6.6 or 7.1; what OS are you running, and can you look at the detailed mysql logs in `/var/log` and see if there are any other clues as to what's going wrong?

**Comment by kakawait** [comment]
I'm using Centos 6.7, but build failed when using `Packer`. I will try again without `Packer` because too long to compute again! And I will post more information

**Comment by geerlingguy** [comment]
Sounds good! And yeah, using Packer can make debugging issues a little tough, especially since the generated VM goes poof!

**Comment by kakawait** [comment]
My bad it works. I have to check if is not a `Packer` issue or other ansible `role` incompatibility

**Comment by kakawait** [comment]
Just FYI I just debug on `Packer`

Even if error is displayed, log is clean (no error)

```
150817 08:45:47 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
150817 08:45:54 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150817  8:45:54 [Warning] 'THREAD_CONCURRENCY' is deprecated and will be removed in a future release.
150817  8:45:54 [Note] /usr/libexec/mysqld (mysqld 5.5.45) starting as process 7651 ...
150817  8:45:54 [Note] Plugin 'FEDERATED' is disabled.
150817  8:45:54 InnoDB: The InnoDB memory heap is disabled
150817  8:45:54 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150817  8:45:54 InnoDB: Compressed tables use zlib 1.2.3
150817  8:45:54 InnoDB: Using Linux native AIO
150817  8:45:54 InnoDB: Initializing buffer pool, size = 256.0M
150817  8:45:54 InnoDB: Completed initialization of buffer pool
150817  8:45:54 InnoDB: highest supported file format is Barracuda.
150817  8:45:55  InnoDB: Waiting for the background threads to start
150817  8:45:56 InnoDB: 5.5.45 started; log sequence number 1961490
150817  8:45:56 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
150817  8:45:56 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
150817  8:45:56 [Note] Server socket created on IP: '0.0.0.0'.
150817  8:45:56 [Note] Event Scheduler: Loaded 0 events
150817  8:45:56 [Note] /usr/libexec/mysqld: ready for connections.
Version: '5.5.45'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server (GPL) by Remi
```

And service is effectively running `mysql -u<user> -p<password>` works fine.

It seems to be an issue on `Packer` (because exporting provisioning from `Packer` and run manually on VM works). I will continue to debug.

PS: I tried without `THREAD_CONCURRENCY` configuration (deprecated), problem persists

**Comment by geerlingguy** [comment]
Interesting... I wonder if it could also be something strange about the networking configuration (IPv4 vs. IPv6, listen on TCP vs Unix socket?) that is causing this problem. I know that has bitten me in the past.

**Comment by kakawait** [comment]
My packer manifest is using centos 6.8 with 480mo memory. It seems to be not enough (because I'm running tomcat in VM too). By incrementing memory to 1go memory you role works perfectly using MySQL >= 5.5.

MySQL >= 5.5 seems to use more memory than <= 5.1
