### ISSUE TITLE
MySQL GPG keys expired

### ISSUE THREAD

**Issue by Naillik13** [geerlingguy/ansible-role-mysql#479]
Since the beginning of 2022, the GPG keys for the official MySQL repository have expired preventing installation or update of MySQL packages.

**Comment by Naillik13** [comment]
https://github.com/geerlingguy/ansible-role-mysql/pull/480

**Comment by geerlingguy** [comment]
Is this only for users who use MySQL packages from their repo? By default this role installs from the system package manager, which doesn't seem to be having any issues.
