### ISSUE TITLE
Fails to start on Ubuntu 15.04 x64 

### ISSUE THREAD

**Issue by kitsunde** [geerlingguy/ansible-role-mysql#49]
At first I tried to do a fairly basic setup:
```yaml
- role: mysql
  mysql_root_password: somepassword
  mysql_users:
    - name: rewards_admin
      host: "%"
      password: somepassword
      priv: "rewards_rewardsmate.*:ALL"
  mysql_databases:
    - name: rewards_rewardsmate
```

It just hangs on:

> TASK: [mysql | Ensure MySQL is started and enabled on boot.] ******************

Then I tried it using only defaults:

```yaml
- role: mysql
```

If I check `service status mysql` it says:

>● mysql.service - MySQL Community Server
>   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
>   Active: activating (start-post) (Result: exit-code) since Thu 2015-08-20 01:48:19 EDT; 4min 5s ago
>  Process: 19538 ExecStart=/usr/bin/mysqld_safe (code=exited, status=2)
>  Process: 19537 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
> Main PID: 19538 (code=exited, status=2);         : 19539 (mysql-systemd-s)
>   CGroup: /system.slice/mysql.service
>           └─control
>             ├─19539 /bin/bash /usr/share/mysql/mysql-systemd-start post
>             └─20715 sleep 1
>
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: 150820 01:48:20 mysqld_safe Logging to '/var/log/mysql.err'.
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: touch: cannot touch '/var/log/mysql.err': Permission denied
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: chmod: cannot access '/var/log/mysql.err': No such file or directory
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: 150820 01:48:20 mysqld_safe Starting mysqld daemon with databas...ysql
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: /usr/bin/mysqld_safe: 126: /usr/bin/mysqld_safe: cannot create ...nied
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: /usr/bin/mysqld_safe: 1: eval: cannot create /var/log/mysql.err...nied
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: touch: cannot touch '/var/log/mysql.err': Permission denied
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: chown: cannot access '/var/log/mysql.err': No such file or directory
>Aug 20 01:48:20 rewardsmate mysqld_safe[19538]: chmod: cannot access '/var/log/mysql.err': No such file or directory
>Aug 20 01:48:20 rewardsmate systemd[1]: mysql.service: main process exited, code=exited, status=2/INVALIDARGUMENT
>Hint: Some lines were ellipsized, use -l to show in full.

This is using a fresh Digital Ocean droplet only installing mysql. Ubuntu 14.04 x64 on DO works just fine.

**Comment by geerlingguy** [comment]
Unfortunately, I only support LTS releases with this role, so I can't guarantee support for 15.04. It looks like the directory structures/installation has changed a bit, but I won't be updating things until the next Ubuntu LTS release drops.

**Comment by kitsunde** [comment]
That's fair enough, but may I suggest including LTS versions supported in the metafile?

**Comment by geerlingguy** [comment]
@kitsunde - Good idea; I'll make that change separately.

**Comment by gravypower** [comment]
For those who come accross this thread googling this problem (as I did) I solved it by updating the mysql_log_error in the defaults/main.yml file to /var/log/mysql/mysql.err.  I am not an expert by any means but this helped me although I don't fully understand the implications of this change.

**Comment by geerlingguy** [comment]
See #58
