### ISSUE TITLE
Mysql can not started after reboot

### ISSUE THREAD

**Issue by legolasleee** [geerlingguy/ansible-role-mysql#490]
My OS is centOS 7.9, and the pid file is placed in directory "/var/run/mariadb" and after I reboot my machine, the directory is deleted, result in the failure of mysql startup. The error message is:
[ERROR] mysqld: Can't create/write to file '/var/run/mariadb/mariadb.pid'
Could I change the pid file location, for example, change it to "/var/lib/mysql"? or is there any other solution that doesn't involve solving this problem manually

**Comment by mmekut** [comment]
Hello @legolasleee, i figured out a solution though manually..............follow my issue on the way forward
