### ISSUE TITLE
Allow custom MariaDB version using upstream repos

### ISSUE THREAD

**Issue by maxxer** [geerlingguy/ansible-role-mysql#499]
MariaDB offers the chance to install a specific version from their repo on the [download page](https://mariadb.org/download/).

It would be great to allow usage of these repo from the role.

**Comment by mmekut** [comment]
I do not think @geerlingguy would respond to this request as his status shows he's busy......

My solution was to create a custom role that installed the official repo of the version I needed.......then I specified that repo in the {{enable_repo}} variable.

This would then install the version of MariaDB that you want.....

....OR browse through the hundreds of forks by other authors and check if they provide such option
