### ISSUE TITLE
Add additional innodb tunables to configuration

### ISSUE THREAD

**Issue by zeryl** [geerlingguy/ansible-role-mysql#504]
I just recently started down the path of Ansible to configure boxes.  One thing that I noticed another role (@bbatsche's mysql role) allows for a couple of items that would really benefit this role, I believe:

- Tunable percentage for InnoDB Buffer Pool Size (i.e. 80% of ram)
- innodb_buffer_pool_instances (ideally, a number. I typically set to the numeric part of the ram, to give 1gb per instance)

With being so new to Ansible, I'm sure there is a way to "override" this today, but I am unaware, and would love to see it natively supported.

**Comment by phanimullapudi** [comment]
@zeryl - You can modify like this - here i am using 75% of my memory

```
innodb_buffer_pool_size = {{ ((ansible_memtotal_mb * 1024) * 0.75)|int|abs }} 
```

**Comment by zeryl** [comment]
Where do you set that? Do I need to edit the role, to set that?
