### ISSUE TITLE
MariaDB not started with log_slow_queries = 1

### ISSUE THREAD

**Issue by drupaladmin** [geerlingguy/ansible-role-mysql#52]
Hi!

We use MariaDB on Debian 8 with slow_log enabled and mysql not started

If we remove log_slow_queries = 1 then it started

What do you think about to remove log_slow_queries = 1 from template my.cnf

**Comment by JorisVanEijden** [comment]
Same issue: "[ERROR] /usr/sbin/mysqld: unknown variable 'log_slow_queries=1'"

log_slow_queries was [deprecated in mysql 5.1.29](http://dev.mysql.com/doc/refman/5.1/en/server-options.html#option_mysqld_log-slow-queries).

+1 for removing it from the template.

**Comment by joshrickert** [comment]
This also occurs under MySQL 5.6.

**Comment by geerlingguy** [comment]
Sorry about this! Should've done it sooner :)
