### ISSUE TITLE
error "couldn't resolve module/action 'mysql_user'" when i used in awx

### ISSUE THREAD

**Issue by yunhai20082008** [geerlingguy/ansible-role-mysql#529]
the project in in :
https://github.com/yunhai20082008/buluma_ansible_mysql
the error is:
```
***********************
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
ok: [web01]
TASK [geerlingguy.mysql : ansible.builtin.include_tasks] ***********************
ERROR! couldn't resolve module/action 'mysql_user'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/requirements_roles/geerlingguy.mysql/tasks/secure-installation.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
---
- name: Ensure default user is present.
  ^ here
```
Do i need to add any collections in yml?

**Comment by yunhai20082008** [comment]
it seems that i use the laste awx with ansible 8 in it.and this is based on ansible 2.9
the newer use "community.mysql.mysql_user: " instead of "mysql_user:"
but I'm not sure，anyone could give me some advises?

**Comment by stefanmalmesjo** [comment]
Late answer, but in case someone else stumbles on it, in my case I had missed to run:

`ansible-galaxy collection install community.mysql`
