### ISSUE TITLE
Remove Python MySQL from package list

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-mysql#54]
If I am correct, it MUST be installed anyway to be able to create databases, etc. Overriding the `mysql_packages` requires to manually include this package is well, which is a possibility to mistake. How about installing it manually in the OS-specific setup?

**Comment by geerlingguy** [comment]
That makes sense to me, since it does need to be around for all the Ansible `mysql_*` module functionality.
