### ISSUE TITLE
Better OS/vendor matrix

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-mysql#55]
I saw a very clever solution for supporting multiple vendors:

https://github.com/HanXHX/ansible-mysql

However, it does not support multiple OS Families.

Here is a support matrix that I could imagine:

- Family: Debian, RedHat
- Vendor: MySQL, MariaDB, Percona, Other (?)

For each OS-Vendor pair you could provide a variable list (packages, daemon, etc) and an installation file (Debian/mysql.yml).

This way you could bundle any number of installation profiles out-of-the-box (without the need for overriding packages for mariadb, etc.)

**Comment by geerlingguy** [comment]
This does look like a good approach (instead of requiring packages to be overridden in almost all cases). I'll see what I can do.

**Comment by sagikazarmark** [comment]
Speaking of being cross-platform: I saw some repository usage configuration for RedHat, but not for Debian. Isn't this something that should also be handled in the playbook (adding custom repository)?

**Comment by geerlingguy** [comment]
@sagikazarmark on RedHat, for installation of specific packages from specific repos, `enablerepo` is more commonly used with the yum task for installation itself, whereas on Debian, it's more common to see people set up repositories and priorities prior to a package's installation, then the package install wouldn't need to use `-t` or anything like that.

In both cases, if you're using a custom repo/PPT, your playbook has to set that up prior to running this role, in `pre_tasks` or in a different role. The configuration is here for convenience's sake on RH-based systems.

**Comment by sagikazarmark** [comment]
Convinced. :wink:
