### ISSUE TITLE
 Can't connect to local MySQL server during root user operations, get "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by csedev** [geerlingguy/ansible-role-mysql#57]
I randomly get this error message while running this role (os_family: Debian).

`TASK: [geerlingguy.mysql | Get list of hosts for the root user.] ************** 
<192.168.76.130> REMOTE_MODULE command mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
failed: [checkpoint] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"root\" ORDER BY (Host=\"localhost\") ASC"], "delta": "0:00:00.005448", "end": "2015-08-30 17:52:43.330309", "rc": 1, "start": "2015-08-30 17:52:43.324861", "stdout_lines": [], "warnings": []}
stderr: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

Right before this task is started, the server is reset.  Based on the type of error, I believe it's caused because the server has not fully started before this task is executed.

Maybe we need to add a wait_for to ensure that server is online before trying to connect?

`- wait_for: port=3306 delay=10`

I wanted to mention that I'm using the VMWare provider, not Virtualbox.  This VMWare provider has its own demons, which may be the cause.  I have not tested with Virtualbox yet.

**Comment by geerlingguy** [comment]
@csedev - I almost exclusively use VMware (7 for now, but upgrading to 8 this week), and haven't had an issue with it. What specific OS are you using?

Once, when I was building MySQL on a Raspberry Pi with an excruciatingly slow MicroSD card, I was running into an issue with slow startup that caused this kind of error. In that case, I set some of the mysql logfile settings lower so the files that were generated weren't so large.

But in this case, if you add that task at the top of the `secure-installation.yml` file, does the role proceed correctly? Also, if you immediately run the playbook again (which would give time for MySQL to finish starting), does it proceed through the steps correctly? If so, then it's definitely slow startup. If not, it could be something else.

Can you also check out the contents of `/var/log/mysql/error.log` (I think that's the file on Debian, can't check right now though) and see if there's anything in there?

**Comment by geerlingguy** [comment]
Note: I just got the same error in a SonarQube role build's default setup here: https://travis-ci.org/geerlingguy/ansible-role-sonar/jobs/151259897

Will dig into this further later, I think!

**Comment by geerlingguy** [comment]
Another fun note; this is only happening on Ubuntu, not on CentOS. Will have to look into _why_.

**Comment by geerlingguy** [comment]
So, I've tested the role with my `geerlingguy/` namespace containers on both VirtualBox and VMware Fusion 8.1, and haven't had any issues. I also found that the Docker/Travis-related problems in the SonarQube are related to https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-242953805

The SonarQube build isn't stuck on MySQL steps anymore.

**Comment by icamys** [comment]
@geerlingguy Found out that the error is present because socket `/var/run/mysqld/mysqld.sock` does not exist. Before using this repo, I've tried to write a role by myself. I succeeded but decided that a cross-platform one would be a better option.

**The first** working and dirty solution was to:

1. Create directory for the socket:
  `sudo mkdir /var/run/mysqld`

2. Create the socket:
  `sudo mkfifo /var/run/mysqld/mysqld.sock`

3. Set mysql user as the owner of the socket directory:
  `sudo chown -R mysql /var/run/mysqld`

4. Change permissions for the socket:
  `chmod 0777 /var/run/mysqld/mysqld.sock`

**The second** clean solution was to destroy vagrant box and to run it with provision again. That solved the issue for me/

**Comment by fubarhouse** [comment]
This might help!

````
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
task path: /etc/ansible/roles/geerlingguy.mysql/tasks/secure-installation.yml:7
Using module file /usr/lib/pymodules/python2.7/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811 `" && echo ansible-tmp-1480909204.55-123075004466811="` echo $HOME/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811 `" ) && sleep 0'
<localhost> PUT /tmp/tmpKNfWmJ TO /root/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811/ /root/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1480909204.55-123075004466811/" > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {
    "changed": false, 
    "cmd": [
        "mysql", 
        "-NBe", 
        "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    ], 
    "delta": "0:00:00.037301", 
    "end": "2016-12-05 03:40:04.679225", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "mysql -NBe \"DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')\"", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", 
    "rc": 1, 
    "start": "2016-12-05 03:40:04.641924", 
    "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
````

**Comment by geerlingguy** [comment]
Can anyone having this issue please provide:

  1. An example reproducible use case—step by step, with any detail as to how you use the role in your playbook.
  2. Environment details—OS, version, where it's hosted (e.g. on VPS, local in VirtualBox, etc.).

Also, please try reproducing the issue with the latest version of the role.

**Comment by kporras07** [comment]
@geerlingguy maybe this helps:
TravisCI build: https://travis-ci.org/ManatiCR/manati-vm/builds/184592416
Repo: https://github.com/ManatiCR/manati-vm/tree/3.0 (Please see 3.0 branch)

This contains role latest version.

Feel free to ask if you need more details.

Maybe the travis tests looks familiar to you :grin:  (it's still in development)

**Comment by geerlingguy** [comment]
@kporras07 - Thanks so much! I've grabbed your repo and will do some testing.

**Comment by geerlingguy** [comment]
@kporras07 - Locally, via Vagrant, I can't get the box to fail... And looking at your `.travis.yml` setup, it looks similar to the MySQL role's.

One difference, just for use with Ubuntu 14.04 on docker, is the use of the initctl-faker script on my MySQL role's tests on Docker/Travis: https://github.com/geerlingguy/ansible-role-mysql/blob/master/tests/test.yml

Tests are also succeeding on Drupal VM's travis runs (which have run a few times today), which seems to indicate maybe there's a configuration difference that's causing the problem, and that it's Docker-specific.

**Comment by kporras07** [comment]
Awesome! I'll take a look later today or during weekend.

**Comment by fubarhouse** [comment]
Yeah I'll give everything I can later today or this weekend - I even have various travis logs you can look at.

**Comment by kporras07** [comment]
great @geerlingguy ! It worked on travis. Thanks :D

**Comment by fubarhouse** [comment]
If docker/travis configs are the cause as you say, I might see if I can get around the problem with your configuration in drupal vm.

**Comment by fubarhouse** [comment]
So I've done some tests in a role I'm developing locally, and I've tried this on your CentOS6, CentOS7 and Ubuntu 16.04 vagrant boxes.

Sadly, I get this error after the role has executed once, but it works fine on the first run.
I didn't notice it on a few runs past the original run, but from that point it simply doesn't work..

Here's the error again:
````
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
task path: /etc/ansible/roles/geerlingguy.mysql/tasks/secure-installation.yml:25
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1483065409.02-65100674522304 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1483065409.02-65100674522304 )" )
127.0.0.1 PUT /tmp/tmpOoUxsJ TO /home/vagrant/.ansible/tmp/ansible-tmp-1483065409.02-65100674522304/command
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-peisvgbkuvxfyevxxgmburdrrurfprbs; LANG=en_US LC_ALL=en_US LC_MESSAGES=en_US /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1483065409.02-65100674522304/command; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1483065409.02-65100674522304/" > /dev/null 2>&1'"'"''
failed: [localhost] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.006064", "end": "2016-12-30 02:36:49.116521", "failed": true, "invocation": {"module_args": {"_raw_params": "mysql -NBe \"DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')\"", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-12-30 02:36:49.110457", "stderr": "ERROR 1142 (42000) at line 1: DELETE command denied to user 'root'@'localhost' for table 'user'", "stdout": "", "stdout_lines": [], "warnings": []}
````

Here's my playbook:
````
- hosts: localhost
  roles:
  - role: geerlingguy.mysql
````

**Comment by geerlingguy** [comment]
@fubarhouse - I noticed it's saying `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'` the second time (indicating MySQL can't be reached, which makes sense if you uninstalled it).

But the first one gives the error `ERROR 1142 (42000) at line 1: DELETE command denied to user 'root'@'localhost' for table 'user'`, which seems to indicate it's possibly a permissions issue or something in the MySQL grants... is it possible for you to look at the database permissions and see if something's messed up there?

Also, can you verify what version of MySQL is running on that server?

**Comment by fubarhouse** [comment]
G'day @geerlingguy,

I can tell you that I've not actually seen a `user` table after using your role recently on fresh installs. It's different at work as we have a downloaded copy of your role (I don't know the date that was last done), but the problem is in fact that there's no user table.

This is a problem, but the real questions are why - and how can I fix it?

**Comment by pgporada** [comment]
I'm hitting the same problem @fubarhouse is hitting.

**Comment by squarelover** [comment]
Has this issue been resolved at all? I still have this, trying to install MySQL 8 on CentOS 7.

**Comment by geerlingguy** [comment]
@squarelover - I haven't run MySQL 8 much yet, so I wouldn't be sure if the problem you're seeing is related to the issues others in this issue have seen, or if it might be something different altogether.

**Comment by geerlingguy** [comment]
Now I get it on Debian 9 (Debian 8 is fine): https://travis-ci.org/geerlingguy/ansible-role-mysql/jobs/445179881#L920

**Comment by ndantonio** [comment]
Hi Everyone / @geerlingguy 

Would like to up this thread. I'm also stucked with this error too:

TASK [geerlingguy.mysql : Disallow root login remotely] ************************
failed: [default] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.005816", "end": "2018-11-07 11:34:45.839892", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "msg": "non-zero return code", "rc": 1, "start": "2018-11-07 11:34:45.834076", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)"], "stdout": "", "stdout_lines": []}

I'm trying to setup MySQL 5.7 in Centos 7.

Thanks.

**Comment by tgadiev** [comment]
As an example of solution you can look at our role here:
https://github.com/lean-delivery/ansible-role-mysql

It's based on this role but seriously refactored and adopted for CentOS 6 & 7. Root password reset procedure is performed by built-in MySQL requests using skip-grant-tables mode. It works correctly for MySQL 5.5, 5.6, 5.7 and MariaDB.

**Comment by pablodav** [comment]
I have noticed this happens only on ubuntu 14.04 docker env when auto testing with molecule and docker in my test environemnts, related to: https://github.com/ansible/ansible/issues/21208#event-1883144200

No issues with same testings on Ubuntu 18.04 and Ubuntu 16.04

**Comment by stevelmcgill** [comment]
Issue still occurs with MySQL 8.0 on RHEL 7.

**Comment by gherosh** [comment]
MySQL 8.4 on Rocky Linux 9 
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
failed: [vagrant] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"ansible_loop_var": "item", "changed": false, "cmd": ["mysqld", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:01:40.851593", "end": "2026-02-14 02:14:03.144810", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "msg": "non-zero return code", "rc": 1, "start": "2026-02-14 02:12:22.293217", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
