### ISSUE TITLE
RHEL/CentOS root password not being set

### ISSUE THREAD

**Issue by stuwil** [geerlingguy/ansible-role-mysql#61]
The fix for #60 introduced a regression where the root password will never, with the default settings, be changed on RHEL/CentOS during the secure installation tasks - causing the subsequent setup tasks requiring the mysql client to fail. The mysql_install_packages registered variable changed flag becomes false by the Debian setup task ([even though it is skipped](https://github.com/ansible/ansible/issues/4297)).

**Comment by geerlingguy** [comment]
Fixed for now via #62 - I hope to switch back to the Ansible `mysql_user` module soon, once I can get it fixed and a new Ansible stable release is out!
