### ISSUE TITLE
MYSQL Users Varibles

### ISSUE THREAD

**Issue by upbeta01** [geerlingguy/ansible-role-mysql#71]
I seem to found some bugs on the mysql role. I have isolated the issue by trying to create 2 db users (1 root-user, 1 db-user).. running both users on the playbook vars gives out an error, running db-user alone gives out an error -- but running root-user alone gives no error. I tried running "mysql" as root and it directs me to the sql-shell which means that  the ".my.cnf" worked properly.

I am running on Ubuntu14 hosted on Digital Ocean Cloud.

---
# PLAYBOOK ERROR

TASK: [ansible-role-mysql | Ensure MySQL users are present.] ******************
failed: [128.199.222.xxx] => (item={'host': 'localhost', 'password': 'testserver-password', 'name': 'testserver-user', 'priv': '_._:ALL'}) => {"failed": true, "item": {"host": "localhost", "name": "testserver-user", "password": "testserver-password", "priv": "_._:ALL"}}
msg: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

FATAL: all hosts have already failed -- aborting

---
# PLAYBOOK VARS

``` javascript
mysql_root_password: P4$$w0rd
overwrite_global_mycnf: yes
mysql_root_password_update: yes
mysql_databases:
 - name: testserver-db
   encoding: latin1
   collation: latin1_general_ci
mysql_users:
# - name: testserver-user
#   host: "localhost"
#   password: testserver-password
#   priv: "testserver-db.*:ALL"

- name: root
host: "localhost"
password: P4$$w0rd
priv: "*.*:ALL"
```

**Comment by aleksandervines** [comment]
I got the same error message. It seems the root password is set to blank, not what "mysql_root_password" specifies

**Comment by georgiana-gligor** [comment]
:+1: 
This is also occuring in my playbook.
I am trying to provision a Centos6.7 and 

```
TASK: [geerlingguy.mysql | Disallow root login remotely] **********************
# ...
failed: [1.2.3.4] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.008636", "end": "2016-02-26 09:31:37.899172", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-02-26 09:31:37.890536", "warnings": []}
stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
# ...
```

**Comment by geerlingguy** [comment]
Hmm... will have to look back into this again. By chance, can you try setting `mysql_root_password_update: yes` for a run?

**Comment by georgiana-gligor** [comment]
Tried that in the afternoon, no luck.

**Comment by d4goxn** [comment]
I ran into something very similar, except that my mysql role wasn't using a password:

```
TASK [geerlingguy.mysql : Disallow root login remotely] ************************
failed: [rumman.co] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-u", "root", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.016040", "end": "2016-10-23 13:47:36.157622", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2016-10-23 13:47:36.141582", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stdout": "", "stdout_lines": [], "warnings": []}
```

I was able to fix it by adding mysql root login credentials to each mysql command.

**Comment by LeonardoGentile** [comment]
As @d4goxn I also have a similar issue, see: #196
Problems usually start from the task _Disallow Root Login Remotely_ with an error like 
```
"ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)",
```
I've tried to use both `mysql_root_password_update: yes` and `mysql_root_password_update: yes` as well as setting and unsetting `mysql_root_password` but I never succeed. 
It seems that `mysql -NBe  "My query here"` always requires a password and somehow either it's not passed at all or the wrong one is passed.

**Comment by hcgweb** [comment]
I ran into this same problem and finally tracked it down to the `/root/.my.cnf` file. It contained the default root password of "root" which is incorrect. My guess is that I must have run the playbook before I set the `mysql_root_password` variable correctly and the file got generated incorrectly. Once I entered the correct password, everything ran just fine.

**Comment by smilesrg** [comment]
```TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
fatal: [db]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}```

```yaml
# provision-db.yaml
---
- hosts: db
  become: true
  become_user: root
  gather_facts: "no"
  vars:
    host_name: db
    db_ip_address: 192.168.33.11
  pre_tasks:
    # We need python2.7 installed to make ansible work correctly.
    - name: 'install python'
      raw: sudo apt-get -y install python-simplejson

    - name: "Install ansible python mysql dependency"
      apt:
        name: python-mysqldb
        state: latest

    - name: "Gather facts"
      setup:

    - name: Update APT package cache
      apt:
        update_cache: "yes"
        cache_valid_time: 3600

    - name: Install aptitude
      apt:
        pkg: aptitude
        state: present

    - name: Update APT to the latest packages
      apt:
        upgrade: safe

    - name: Set host name to proxy
      hostname:
        name: "{{host_name}}"

    - name: Setup host file
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{db_ip_address}} db"
        line: "{{db_ip_address}} db"
        state: present
  roles:
    - role: geerlingguy.mysql
      mysql_root_password: "vagrant"
      mysql_bind_address: "{{host_name}}"
      mysql_databases:
        - name: wireless
          encoding: latin1
          collation: latin1_general_ci
      mysql_users:
        - name: root
          host: "%"
          priv: "*.*:ALL"
          password: "vagrant"
```
