### ISSUE TITLE
Add configuration option to allow remote login

### ISSUE THREAD

**Issue by BrianGilbert** [geerlingguy/ansible-role-mysql#79]
For local dev I can't think of any reason why you wouldn't want to allow this?

**Comment by geerlingguy** [comment]
You can always set the variables for the port/address to allow anyone to log in through any network interface you choose:

```
port = {{ mysql_port }}
bind-address = {{ mysql_bind_address }}
datadir = {{ mysql_datadir }}
socket = {{ mysql_socket }}
pid-file = {{ mysql_pid_file }}
```

Another option, which is much more secure, is to use SSH to log into the server and manage MySQL through that SSH tunneled connection; see how this is done with Drupal VM here: http://docs.drupalvm.com/en/latest/extras/mysql/
