### ISSUE TITLE
Problems with secure-installation.yml on Debian

### ISSUE THREAD

**Issue by simonszu** [geerlingguy/ansible-role-mysql#81]
Hi,

currently i am "migrating" to ansible, speak: I am defining the status quo of my systems in ansible to get a base for further reconfiguring them. My goal is to have an ansible setup where my playbooks run, and nothing changes. 

So, i am using your module to set up a MariaDB server on debian. The server i have manually set up has set a root password since its installation. Debian's dpkg-config workflow asks for it during the installation. 

So, that's a problem for your role. The secure-installation.yml workflow assumes for all its tasks that there is no root password set, so the existing MariaDB declines the login for all these tasks and they fail. 

I would have submitted a pull request with handling this situation, but to be honest, i am unsure about it. 
Unsure how ansible's automatic apt workflow handles the dpkg-config stuff (you know, these ncurses dialog boxes where some initial values are asked and set up). Maybe calling apt remotely via ansible does not trigger this setup step, and the SQL installation is inherently unsafe after installation and needs the secure-installation.yml workflow. 

But, to be honest, i question the idempotence of this workflow. The secure-installation workflow is called everytime, but after the first run, a root password should be set by the second task. However, in all subsequent runs, the first task runs again and tries to login into the server without providing a password, and will fail. 

So, my suggestion is: If the mysql client tries to login with a given password, and no password is required, it will still succeed. The role has a `mysql_root_password` default variable which can be overridden by the user. What about submitting this password every time a task calls the mysql shell command to do something with the database?

**Comment by simonszu** [comment]
Ah, nevermind. I didn't see the task that copies the user's .my.cnf. 
So i assume, my initial, manuall installation isn't complete, since i don't had this .my.cnf, heh? ;)

**Comment by geerlingguy** [comment]
@simonszu - Correct! And don't worry about it; this role is a bit more complex than many others (necessarily so, since setting up MySQL/MariaDB correctly is a little daunting), and feel free to open issues for anything else you see awry!
