### ISSUE TITLE
Use default configuration of the installation

### ISSUE THREAD

**Issue by mjanser** [geerlingguy/ansible-role-mysql#83]
Now it's not possible to use some default configuration values from the installation because they are always written to the config file according to the variables. Is it possible to change this so that config value are only written if they aren't empty (with default: empty)?

**Comment by geerlingguy** [comment]
With the way I currently have the role structured, I'm replacing the entire `my.cnf` file, so there's no way (with that approach) to leave any of the existing file intact. I would suggest if you need a different level of customization, you can fork this role or create/use a different one, as I'd rather not try to set up the my.cnf file override differently (at least not in the near term).
