### ISSUE TITLE
MySQL 5.7.x deprecated variables

### ISSUE THREAD

**Issue by pporada-gl** [geerlingguy/ansible-role-mysql#85]
I'm on CentOS 7 and have installed MySQL 5.7.10 from the mysql-community-release repository located at https://dev.mysql.com/downloads/repo/yum/. That repo was installed successfully via a different ansible role.

I receive the following errors upon ansible starting mysqld
```
2016-02-04T16:15:37.446686Z 0 [Note] InnoDB: not started
2016-02-04T16:15:37.446876Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2016-02-04T16:15:37.446885Z 0 [ERROR] unknown variable 'innodb_additional_mem_pool_size=20M'
2016-02-04T16:15:37.446894Z 0 [ERROR] Aborting
...
2016-02-04T16:13:34.139702Z 0 [Note] InnoDB: not started
mysqld: Table 'mysql.plugin' doesn't exist
2016-02-04T16:13:34.139796Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
2016-02-04T16:13:34.139897Z 0 [ERROR] unknown variable 'thread_concurrency=2'
2016-02-04T16:13:34.139901Z 0 [ERROR] Aborting
```

Here are the mysql docs stating the removal date of some of the variables in your default my.cnf
http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_additional_mem_pool_size
http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_thread_concurrency

Would it be possible to provide our own my.cnf as opposed to having my.cnf includes or having the option to override all of the variables you set?

**Comment by FinBoWa** [comment]
I have to ask the obvious: why not just run maria db on centos 7?

Anyways: the EASIEST way to override stuff is to fork the repo and edit to suit your needs and then install that with the requirements.yml file to a specific folder.

As an example: 

```yaml
- src: https://github.com/Focus-Flow/ansible-role-daemonize
  version: 1.0.0+0.0.1
  path: ansible-roles/ansible-roles-remote
  name: geerlingguy.daemonize
```
And then add this to your ansible.cfg file (or create it where you run playbook):

```
[defaults]
roles_path = ansible-roles/ansible-roles-local:ansible-roles/ansible-roles-remote
```
That's how we fixed/extended that specific role, but allow roles that depend on it to work correctly as we didn't change the naming of the role.

**Comment by geerlingguy** [comment]
I'm closing this issue in favor of https://github.com/geerlingguy/ansible-role-mysql/issues/63, where I'll fix this issue and any other outliers that prevent this role from running correctly with MySQL 5.7.x under systemd.
