### ISSUE TITLE
Getting warnings in Ansible 2

### ISSUE THREAD

**Issue by keyurshah** [geerlingguy/ansible-role-mysql#86]
Hello,

I know it's not supported yet, but everything seems to work except for 2 tasks that seem to be getting a variable from the prior task. This is the warning I get:

<code>
TASK [geerlingguy.mysql : Update MySQL root password for localhost root account.] ***
[DEPRECATION WARNING]: Skipping task due to undefined attribute, in the future this will be a fatal error.. This
feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] ***
ok: [db01]

TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********
skipping: [db01]

TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***********************
[DEPRECATION WARNING]: Skipping task due to undefined attribute, in the future this will be a fatal error.. This
feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
</code>

Thank you very much.

**Comment by geerlingguy** [comment]
Interesting... I've been running this role with Ansible 2.x for the past few months and haven't seen those particular warnings—can you give any more details about your environment/variables? (Especially what OS/version you're running).

**Comment by keyurshah** [comment]
ok, thanks. I was trying it from a local vagrant installation in Ubuntu, connecting to a Ubuntu 14 LTS  on Linode. Perhaps it has to do with the Vagrant / Windows installation. I know there are some permission issues that can pop up. 

I'll have to try it from a non Vagrant installation to confirm. Can I ask where you run your scripts from?

**Comment by geerlingguy** [comment]
@keyurshah - I run from a few different locations:

  - Within a vagrant VM (using `geerlingguy/ubuntu12`, `geerlingguy/ubuntu14` and `geerlingguy/centos7` base boxes).
  - From my local Mac, controlling servers in DigitalOcean and AWS
  - Within a Jenkins environment, controlling servers in DigitalOcean

**Comment by keyurshah** [comment]
ok, thank you. I'll try running it from a Ubuntu LTS machine that's not through vagrant. I think it might be a Vagrant / Windows issue.
