### ISSUE TITLE
RHEL/CentOS 7 uses MariaDB instead of MySQL

### ISSUE THREAD

**Issue by keuz** [geerlingguy/ansible-role-mysql#9]
Hello!

First of all thanks for you effort! 

I found a small issue. On Centos 7 "default" Mysql is 'mariadb-server' as far as I understand.
So it falls with:
```
failed: [********] => (item=mysql,mysql-server,MySQL-python) => {"changed": false, "failed": true, "item": "mysql,mysql-server,MySQL-python", "rc": 0, "results": ["mariadb-5.5.40-1.el7_0.x86_64 providing mysql is already installed"]}
msg: No Package matching 'mysql-server' found available, installed or updated

FATAL: all hosts have already failed -- aborting
```

Some topics about mysql package in Centos 7: 
https://www.centos.org/forums/viewtopic.php?f=48&t=47394
https://www.digitalocean.com/community/questions/can-t-install-mysql-on-centos-7

**Comment by JorisVanEijden** [comment]
Can the mysql_packages be moved from vars to defaults?
I'd like to use mysql56u from IUS for some machines.

**Comment by geerlingguy** [comment]
I've set `mysql_packages` in a way that can be overridden, and I'll soon be working on getting the rest of the role working correctly on CentOS 7 / MariaDB.

**Comment by geerlingguy** [comment]
See #38 .
