### ISSUE TITLE
mysql_datadir is not respected

### ISSUE THREAD

**Issue by abriel** [geerlingguy/ansible-role-mysql#95]
Hello,

I try to use non standard path for data. I set up `mysql_datadir` , which reflects in configuration,
but data has not moved or created, so start is failed.

Thanks.

**Comment by geerlingguy** [comment]
@abriel - This role is only meant to set up the initial configuration or be adapted to an existing configuration. I don't intend to support things like moving config locations, moving the datadir, etc.—for that, you'll need to write a separate task-specific playbook, as it's a bit more involved, requiring service shutdown, file copies, reconfiguration, then restart.
