### ISSUE TITLE
use /etc/mysql/conf.d instead of overriding system file

### ISSUE THREAD

**Issue by drzraf** [geerlingguy/ansible-role-mysql#98]
That's what `conf.d/*` directories are for.
They let administrator / administrator tools manage configuration and keep it across upgrades.
Any sane system's `/etc/mysql/my.cnf` contains

```
!includedir /etc/mysql/conf.d/
```

Having role's configuration self-contained inside a `/etc/mysql/conf.d/42-ansible.conf` file would be a nice maintenance win.

**Comment by geerlingguy** [comment]
True - one thing to keep in mind is that this role needs to work correctly across CentOS 6/7, Ubuntu 12.04/14.04, Debian 7/8, and a few other OSes (though these others with less official support).

If all of them include /conf.d/* by default (or we can easily support that with a basic `lineinfile`, and if we can make sure that duplicate configuration directives allow the role-powered template to override any default setting in the main `my.cnf`, then I'm happy to make the change.

I don't have time to do the testing right now, but might sooner or later—if someone else can do so and get a PR up and running that has a fairly simple upgrade path, it will require a new major role version, but I'd be willing to go that route.

**Comment by drzraf** [comment]
I just read https://dev.mysql.com/doc/refman/5.7/en/option-files.html (MySQL 5.7).
About `includedir`:
> there is no guarantee about the order in which the option files in the directory will be read.   
But is it a problem. If there would be guarantees, we would name the file `999-ansible.cnf` but that would be bad.

These directives are supported [since MySQL 5.0.4](https://dev.mysql.com/doc/refman/5.0/en/option-files.htmlhttps://dev.mysql.com/doc/refman/5.0/en/option-files.html)


In case of emergency, an admin wanting to change a value would have to fight ansible or fighting the lexicography, editing said file, or editing the main my.cnf).
I think it's fine to offer realistically to be treated last, but not to force manual operation, choosing a name like : `89-ansible-try-to-keep-me-last.cnf`

There are other solution to force ansible override (like adding another  `include` after the `includir`, but like said above, chances are that it get in the feet of the the adminsys one day it shouldn't.

Since it's something impact the role quite a bit (BC-break) I'd rather not issue a PR myself, but I'm fully in favor of such change.

**Comment by xipmix** [comment]
It's worth remembering that one can just reload specific files at the bottom of ```my.cnf``` if they need to be in a given order. Something like...
```
# load everything
! includedir /etc/mysql/conf.d
{% if ( "{{ msql_ordered_cfgs }}" != "" ) %}
# these files need to be loaded in this specific order
{%- for item in mysql_ordered_cfgs %}
!include {{ item }}
{%- endfor %}
{% endif %}
```
This way you don't care what the ```includedir``` evaluation order is...
